--
-- export skill costs data
--

local out = io.open("../Data/GoldRespecPrices.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Skill costs data (c) Grinding Gear Games\n\n')
out:write('return {\n')

for c in dat("GoldRespecPrices"):Rows() do
	out:write('\t[', c.Level, '] = {\n')
	out:write('\t\tCost = ', c.Cost, ',\n')
	out:write('\t},\n')
end

out:write('}\n')
out:close()

print("Gold prices data exported.")
