local function makeSkillMod(modName, modType, modVal, flags, keywordFlags, ...)
	return {
		name = modName,
		type = modType,
		value = modVal,
		flags = flags or 0,
		keywordFlags = keywordFlags or 0,
		...
	}
end
local function makeFlagMod(modName, ...)
	return makeSkillMod(modName, "FLAG", true, 0, 0, ...)
end
local function makeSkillDataMod(dataKey, dataValue, ...)
	return makeSkillMod("SkillData", "LIST", { key = dataKey, value = dataValue }, 0, 0, ...)
end
dofile("../Data/Global.lua")
local skillStatMap = LoadModule("../Data/SkillStatMap.lua", makeSkillMod, makeFlagMod, makeSkillDataMod)

if not loadStatFile then
	dofile("statdesc.lua")
end
-- Tamed beasts are itemised captured monsters; their mods render with this description file
loadStatFile("monster_stat_descriptions.csd")

local function tableToString(tbl, pre)
	pre = pre or ""
	local tableString = "{ "
	local outNames = { }
	for name in pairs(tbl) do
		table.insert(outNames, name)
	end
	table.sort(outNames)
	for _, name in ipairs(outNames) do
		if type(tbl[name]) == "table" then
			tableString = tableString .. tableToString(tbl[name], pre .. name .. ".")
		else
			if _ > 1 then
				tableString = tableString .. ", "
			end
			tableString = tableString .. pre .. name .. " = " .. (type(tbl[name]) == "string" and '"' or '') .. tostring(tbl[name]) .. (type(tbl[name]) == "string" and '"' or '')
		end
	end
	return tableString .. " }"
end

local function escapeString(text)
	return text:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub("%s*[\r\n]+%s*", " ")
end

-- GGG keyword markup is stripped with the shared escapeGGGString (Modules/Common.lua,
-- loaded by the export tool) — the same function the importer applies to incoming lines,
-- so stored display lines always match imported ones verbatim.

local MONSTER_DOMAIN = 3 -- see modDomains in enums.lua
local GEN_PREFIX = 1
local GEN_SUFFIX = 2

-- Player-facing display names for monster mods; this is the same keyword popup
-- system the character API uses for its "[ModId|Display]" markup. The popup
-- Description is the full explanation shown in-game (good tooltip text).
local popupNames, popupDescriptions = { }, { }
for popup in dat("KeywordPopups"):Rows() do
	if popup.Name and popup.Name ~= "" then
		popupNames[popup.Id] = popup.Name
	end
	if popup.Description and popup.Description ~= "" then
		popupDescriptions[popup.Id] = popup.Description
	end
end
-- Nameplate lines for rare monster mods without keyword popups (e.g. "Periodically
-- unleashes [Cold|Ice]"); the table name is a PoE1 leftover GGG reuses in PoE2
local archNames = { }
for archMod in dat("ArchnemesisMods"):Rows() do
	if archMod.Id and archMod.Name and archMod.Name ~= "" then
		archNames[archMod.Id.Id] = archMod.Name
	end
end

local out = io.open("../Data/TamedBeastMods.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Path of Building\n')
out:write('--\n')
out:write('-- Tamed Beast (Companion) Modifier Data\n')
out:write('-- Monster data (c) Grinding Gear Games\n')
out:write('\n')
out:write('local mods, mod, flag = ...\n')

local exported, unmappedStats = 0, { }
for modRow in dat("Mods"):Rows() do
	if modRow.Domain == MONSTER_DOMAIN and (modRow.GenerationType == GEN_PREFIX or modRow.GenerationType == GEN_SUFFIX) and not modRow.Id:match("Royale") then
		-- Render description lines at min roll; min == max keeps the text free of "(min-max)" ranges
		-- so the importer can match display lines verbatim
		local stats = { }
		for i = 1, 6 do
			if modRow["Stat"..i] then
				stats[modRow["Stat"..i].Id] = { min = modRow["Stat"..i.."Value"][1], max = modRow["Stat"..i.."Value"][1] }
			end
		end
		if modRow.Type then
			stats.Type = modRow.Type
		end
		local descLines = describeStats(stats)
		local popupName = popupNames[modRow.Id]
		local archName = archNames[modRow.Id] and escapeGGGString(archNames[modRow.Id])
		local popupDescription = popupDescriptions[modRow.Id] and escapeGGGString(popupDescriptions[modRow.Id])
		if popupName or archName or descLines[1] or modRow.Name ~= "" then
			local name = popupName or archName or (modRow.Name ~= "" and modRow.Name) or descLines[1]
			-- A mod can only be rolled (and thus appear on a captured beast) if some monster
			-- tag carries a positive spawn weight; script-applied mods (abyss etc.) and the
			-- "PlayerMonster*" twins are all-zero. Unnamed placeholders are not selectable.
			local rollable = false
			for _, weight in ipairs(modRow.SpawnWeight) do
				if weight > 0 then
					rollable = true
					break
				end
			end
			out:write('\nmods["', modRow.Id, '"] = {\n')
			out:write('\tname = "', escapeString(name), '",\n')
			if rollable and name ~= "TBD" then
				out:write('\trollable = true,\n')
			end
			out:write('\ttype = "', modRow.GenerationType == GEN_PREFIX and "Prefix" or "Suffix", '",\n')
			local tier = tonumber(modRow.Id:match("(%d+)$"))
			if tier then
				out:write('\ttier = ', tier, ',\n')
			end
			out:write('\tstatDescriptions = {\n')
			if archName and archName ~= name then
				out:write('\t\t"', escapeString(archName), '",\n')
			end
			if popupDescription then
				out:write('\t\t"', escapeString(popupDescription), '",\n')
			end
			for _, line in ipairs(descLines) do
				out:write('\t\t"', escapeString(line), '",\n')
			end
			out:write('\t},\n')
			out:write('\tmodList = {\n')
			for i = 1, 6 do
				if modRow["Stat"..i] then
					local statId = modRow["Stat"..i].Id
					local modStats = ' [' .. statId .. ' = ' .. modRow["Stat"..i.."Value"][1] .. ']'
					if skillStatMap[statId] then
						local newMod = skillStatMap[statId][1]
						out:write('\t\tmod("', newMod.name, '", "', newMod.type, '", ', newMod.value and type(newMod.value) ~= "boolean" and tableToString(newMod.value) or (skillStatMap[statId].value or modRow["Stat"..i.."Value"][1] * (skillStatMap[statId].mult or 1) / (skillStatMap[statId].div or 1)), ', ', newMod.flags or 0, ', ', newMod.keywordFlags or 0)
						for _, extra in ipairs(newMod) do
							out:write(', ', tableToString(extra))
						end
						out:write('), -- ', modRow.Id, modStats, '\n')
					else
						out:write('\t\t-- ', modRow.Id, modStats, '\n')
						unmappedStats[statId] = (unmappedStats[statId] or 0) + 1
					end
				end
			end
			out:write('\t},\n')
			out:write('}\n')
			exported = exported + 1
		end
	end
end
out:close()

print("Tamed beast mod data exported: " .. exported .. " mods.")
local unmappedList = { }
for statId, count in pairs(unmappedStats) do
	table.insert(unmappedList, { statId = statId, count = count })
end
table.sort(unmappedList, function(a, b) return a.count > b.count end)
if unmappedList[1] then
	print(#unmappedList .. " stats had no SkillStatMap entry (emitted as comments):")
	for _, entry in ipairs(unmappedList) do
		print("  " .. entry.statId .. " (x" .. entry.count .. ")")
	end
end
