-- This file is automatically generated, do not edit!
-- Path of Building
--
-- World Area Data (c) Grinding Gear Games
--

-- Step 0: Read Spectres.lua to get spectre IDs
local importedSpectres = {}
local file = io.open("../Data/Spectres.lua", "r")
if file then
	for line in file:lines() do
		local id = line:match('minions%[%"(.-)%"%]')
		if id then
			importedSpectres[id] = true
		end
	end
	file:close()
end

-- Step 1: Build packId -> monster names (spectre-eligible + imported only)
local packIdToMonsters = {}

for entry in dat("MonsterPackEntries"):Rows() do
	if entry.MonsterPacksKey and entry.MonsterVarietiesKey then
		local packId = entry.MonsterPacksKey.Id
		local monVar = entry.MonsterVarietiesKey
		if packId and monVar and monVar.Name and monVar.Name ~= "" and not monVar.NotSpectre and importedSpectres[monVar.Id] then
			packIdToMonsters[packId] = packIdToMonsters[packId] or {}
			table.insert(packIdToMonsters[packId], monVar.Name)
		end
	end
end

for pack in dat("MonsterPacks"):Rows() do
	local packId = pack.Id
	local list = packIdToMonsters[packId] or {}
	local seen = {}
	for _, name in ipairs(list) do
		seen[name] = true
	end

	local function addIfSpectre(mon)
		if mon and mon.Name and mon.Name ~= "" and not mon.NotSpectre and importedSpectres[mon.Id] and not seen[mon.Name] then
			table.insert(list, mon.Name)
			seen[mon.Name] = true
		end
	end

	if pack.AdditionalMonsters then
		for _, mon in ipairs(pack.AdditionalMonsters) do
			addIfSpectre(mon)
		end
	end
	if pack.BossMonsters then
		for _, mon in ipairs(pack.BossMonsters) do
			addIfSpectre(mon)
		end
	end

	packIdToMonsters[packId] = list
end

-- Step 2: areaId -> monster names
local areaIdToMonsters = {}

for pack in dat("MonsterPacks"):Rows() do
	if pack.WorldAreas then
		for _, areaRef in ipairs(pack.WorldAreas) do
			local areaId = areaRef.Id
			if areaId then
				areaIdToMonsters[areaId] = areaIdToMonsters[areaId] or {}
				local seen = areaIdToMonsters[areaId .. "_seen"] or {}
				for _, name in ipairs(packIdToMonsters[pack.Id] or {}) do
					if not seen[name] then
						table.insert(areaIdToMonsters[areaId], name)
						seen[name] = true
					end
				end
				areaIdToMonsters[areaId .. "_seen"] = seen
			end
		end
	end
end

-- Step 3: EndGameMaps
for map in dat("EndGameMaps"):Rows() do
	local areaRefs = {}
	if map.WorldArea then
		table.insert(areaRefs, map.WorldArea)
	end
	if map.WorldArea then
		for _, area in ipairs(map.WorldArea) do
			table.insert(areaRefs, area)
		end
	end
	if map.WorldAreaBoss then
		table.insert(areaRefs, map.WorldAreaBoss)
	end
	for _, area in ipairs(areaRefs) do
		local areaId = area.Id
		areaIdToMonsters[areaId] = areaIdToMonsters[areaId] or {}
		local seen = areaIdToMonsters[areaId .. "_seen"] or {}
		if map.NativePacks then
			for _, pack in ipairs(map.NativePacks) do
				for _, name in ipairs(packIdToMonsters[pack.Id] or {}) do
					if not seen[name] then
						table.insert(areaIdToMonsters[areaId], name)
						seen[name] = true
					end
				end
			end
		end
		areaIdToMonsters[areaId .. "_seen"] = seen
	end
end


-- Step 4: Output
local out = io.open("../Data/WorldAreas.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Path of Building\n')
out:write('-- World Area Data (c) Grinding Gear Games\n\n')
out:write('local worldAreas, _ = ...\n\n')

for area in dat("WorldAreas"):Rows() do
	if area.Name and area.Name ~= "NULL" and area.Id then
		local monsters = areaIdToMonsters[area.Id] or {}
		local tags = {}
		local isMap = false
		if area.Tags and #area.Tags > 0 then
			for _, tag in ipairs(area.Tags) do
				table.insert(tags, '"' .. tag.Id .. '"')
				if tag.Id == "map" then
					isMap = true
				end
			end
		end
		out:write('worldAreas["' .. area.Id .. '"] = {\n')
		local suffix = ""
		if isMap then
			suffix = " (Map)"
		elseif area.Act and area.Act ~= 10 then
			suffix = " (Act " .. tostring(area.Act) .. ")"
		end
		out:write('\tname = "' .. area.Name .. suffix .. '",\n')
		out:write('\tbaseName = "' .. area.Name .. '",\n')
		if area.Description and area.Description ~= "" then
			out:write('\tdescription = "' .. area.Description .. '",\n')
		end
		out:write('\ttags = { ' .. table.concat(tags, ", ") .. ' },\n')
		out:write('\tact = ' .. tostring(area.Act or 0) .. ',\n')
		out:write('\tlevel = ' .. tostring(area.AreaLevel or 1) .. ',\n')
		out:write('\tisMap = ' .. tostring(isMap) .. ',\n')
		out:write('\tisHideout = ' .. tostring(area.IsHideout) .. ',\n')
		out:write('\tmonsterVarieties = {\n')
		local seen = {}
		for _, name in ipairs(monsters) do
			if not seen[name] then
				out:write('\t\t"' .. name .. '",\n')
				seen[name] = true
			end
		end
		out:write('\t},\n')
		out:write('}\n\n')
	end
end

out:write('return worldAreas\n')
out:close()

print("World Areas exported.")
