local t_insert = table.insert

local M = {}

---@alias StringifyTypes string | number | boolean | nil | table<StringifyTypes, StringifyTypes>

-- Converts a table to a string which will be valid Lua. The result will ipairs to utilise the array
-- syntax when applicable, and will sort other keys.
--- @param value StringifyTypes
--- @param allowNewlines boolean? Determines if multi-line strings should be allowed. By default newlines are converted to spaces.
--- @return string
function M.stringify(value, allowNewlines, tabs)
	local valType = type(value)
	if not tabs then
		tabs = 0
	end
	if valType == "string" then
		if allowNewlines and value:find("\n") then
			return '[['..value..']]'
		else
			local s = value:gsub("\n", " ")
			return '"'..s..'"'
		end
	elseif valType == "boolean" or valType == "nil" or valType == "number" then
		return tostring(value)
	elseif valType == "table" then
		local s = "{\n";
		-- ipairs compatible keys are done first so we can use the array syntax for them
		local arrayKeys = {}
		local indent = string.rep("\t", tabs)
		for k, v in ipairs(value) do
			arrayKeys[k] = true
			s = s..indent..M.stringify(v, allowNewlines, tabs + 1) ..",\n"
		end

		local mapKeys = { }
		for key in pairs(value) do t_insert(mapKeys, key) end
		table.sort(mapKeys, function (a, b)
			return tostring(a) < tostring(b)
		end)

		for _, k in ipairs(mapKeys) do
			if not arrayKeys[k] then
				local keyStr = M.stringify(k, allowNewlines)
				if keyStr:find("^%[") then
					-- multiline strings as keys need the space around the key value to parse correctly
					s = s..indent.."[ "..keyStr.." ] = "
				else
					s = s..indent.."["..keyStr.."] = "
				end
				s = s..M.stringify(value[k], allowNewlines, tabs + 1)..",\n"
			end
		end
		return s..string.rep("\t", tabs-1).."}"
	else
		error("Disallowed stringify type "..valType)
	end
end

---@param fileName
---@param table StringifyTypes
---@param description? string A string which will be passed to string.format and which should describe what this file contains. Multi-line strings are supported.
---@param allowMultiLine? boolean Whether multi-line strings should be allowed. If not, they are converted to spaces.
---@return boolean success
function M.saveTableToFile(fileName, table, description, allowMultiLine)
	local f, openErr = io.open(fileName, "w")
	if not f then
		error(string.format("Could not open %s for writing table: %s", fileName, openErr))
	end
	local descFormatted = ""
	if description then
		-- add newline at the end
		if description:sub(-1) ~= "\n" then
			description = description .. "\n"
		end
		-- prepend lines with comments
		for line in description:gmatch("(.-)\n") do
			descFormatted = descFormatted .. "-- " .. line .. "\n"
		end
	end
	local template = [[-- This file is automatically generated, do not edit!
-- Game data (c) Grinding Gear Games

%s
-- spell-checker: disable
return %s
]]

	local contents = string.format(template, descFormatted, M.stringify(table, allowMultiLine, 1))

	local _, writeErr = f:write(contents)

	if writeErr then
		error(string.format("Failed to write to %s: %s", fileName, writeErr))
	end

	return f:close() or false
end

return M