-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Crimson Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "(2-4) Life Regeneration per second",
	implicitModTypes = { { "flat_life_regen", "resource", "life" }, },
	req = { },
}
itemBases["Azure Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "(20-30)% increased Mana Regeneration Rate",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["Amber Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(10-15) to Strength",
	implicitModTypes = { { "attribute" }, },
	req = { level = 8, },
}
itemBases["Jade Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(10-15) to Dexterity",
	implicitModTypes = { { "attribute" }, },
	req = { level = 8, },
}
itemBases["Lapis Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(10-15) to Intelligence",
	implicitModTypes = { { "attribute" }, },
	req = { level = 8, },
}
itemBases["Lunar Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(20-30) to maximum Energy Shield",
	implicitModTypes = { { "defences", "energy_shield" }, },
	req = { level = 14, },
}
itemBases["Bloodstone Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(30-40) to maximum Life",
	implicitModTypes = { { "resource", "life" }, },
	req = { level = 18, },
}
itemBases["Stellar Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(5-7) to all Attributes",
	implicitModTypes = { { "attribute" }, },
	req = { level = 24, },
}
itemBases["Solar Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(10-15) to Spirit",
	implicitModTypes = { {  }, },
	req = { level = 30, },
}
itemBases["Gold Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "(12-20)% increased Rarity of Items found",
	implicitModTypes = { { "drop" }, },
	req = { level = 35, },
}
itemBases["Pearlescent Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(7-10)% to all Elemental Resistances",
	implicitModTypes = { { "cold_resistance", "elemental_resistance", "fire_resistance", "lightning_resistance", "elemental", "fire", "cold", "lightning", "resistance" }, },
	req = { level = 30, },
}
itemBases["Veridical Chain"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(30-40) to maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	req = { level = 18, },
}
itemBases["Runemastered Veridical Chain"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, runeforged = true, },
	implicit = "+(30-40) to maximum Runic Ward\n+(2-3)% to Maximum Cold Resistance",
	implicitModTypes = { { "runic_ward" }, { "cold_resistance", "elemental_resistance", "elemental", "cold", "resistance" }, },
	req = { level = 18, },
}
itemBases["Runemastered Veridical Chain"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, runeforged = true, },
	implicit = "+(30-40) to maximum Runic Ward\n+(1-2) to Level of all Cold Skills",
	implicitModTypes = { { "runic_ward" }, { "elemental", "cold", "gem" }, },
	req = { level = 18, },
}
itemBases["Runemastered Veridical Chain"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, runeforged = true, },
	implicit = "(15-20)% increased maximum Runic Ward",
	implicitModTypes = { { "runic_ward" }, },
	req = { },
}
itemBases["Lament Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Prefix Modifier allowed",
	implicit = "Grants Skill: Level (1-20) Arctic Armour",
	implicitModTypes = { {  }, },
	req = { level = 42, },
}
itemBases["Portent Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Suffix Modifier allowed",
	implicit = "Grants Skill: Level (1-20) Wolf Pack",
	implicitModTypes = { {  }, },
	req = { level = 42, },
}
itemBases["Absent Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Prefix Modifier allowed\n-1 Suffix Modifier allowed",
	implicit = "Grants Skill: Level (1-20) Cast on Elemental Ailment",
	implicitModTypes = { {  }, {  }, },
	req = { level = 49, },
}
itemBases["Corona Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "This item gains bonuses from Socketed Items as though it was a Helmet",
	implicitModTypes = { {  }, },
	req = { level = 40, },
}
itemBases["Dusk Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+1 Prefix Modifier allowed\n-1 Suffix Modifier allowed",
	implicitModTypes = { {  }, {  }, },
	req = { },
}
itemBases["Gloam Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Prefix Modifier allowed\n+1 Suffix Modifier allowed",
	implicitModTypes = { {  }, {  }, },
	req = { },
}
itemBases["Penumbra Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+2 Prefix Modifiers allowed\n-2 Suffix Modifiers allowed",
	implicitModTypes = { {  }, {  }, },
	req = { },
}
itemBases["Tenebrous Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-2 Prefix Modifiers allowed\n+2 Suffix Modifiers allowed",
	implicitModTypes = { {  }, {  }, },
	req = { },
}
itemBases["Twisted Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Prefix Modifier allowed",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Distorted Amulet"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "-1 Suffix Modifier allowed",
	implicitModTypes = { {  }, },
	req = { },
}
