-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Antidote Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you become Poisoned",
	implicitModTypes = { },
	charm = { duration = 3, chargesUsed = 30, chargesMax = 80, buff = { "Grants Immunity to Poison" }, },
	req = { level = 24, },
}
itemBases["Dousing Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you become Ignited",
	implicitModTypes = { },
	charm = { duration = 3, chargesUsed = 60, chargesMax = 80, buff = { "Grants Immunity to Ignite" }, },
	req = { level = 32, },
}
itemBases["Grounding Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you become Shocked",
	implicitModTypes = { },
	charm = { duration = 2.2, chargesUsed = 80, chargesMax = 80, buff = { "Grants Immunity to Shock" }, },
	req = { level = 32, },
}
itemBases["Ruby Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you take Fire Damage from a Hit",
	implicitModTypes = { },
	charm = { duration = 4, chargesUsed = 40, chargesMax = 80, buff = { "+25% to Fire Resistance" }, },
	req = { level = 5, },
}
itemBases["Sapphire Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you take Cold Damage from a Hit",
	implicitModTypes = { },
	charm = { duration = 4, chargesUsed = 40, chargesMax = 80, buff = { "+25% to Cold Resistance" }, },
	req = { level = 5, },
}
itemBases["Silver Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you are affected by a Slow",
	implicitModTypes = { },
	charm = { duration = 3, chargesUsed = 40, chargesMax = 80, buff = { "Your speed is unaffected by slows" }, },
	req = { level = 10, },
}
itemBases["Staunching Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you start Bleeding",
	implicitModTypes = { },
	charm = { duration = 3, chargesUsed = 60, chargesMax = 80, buff = { "Grants Immunity to Bleeding" }, },
	req = { level = 18, },
}
itemBases["Stone Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you become Stunned",
	implicitModTypes = { },
	charm = { duration = 2.5, chargesUsed = 40, chargesMax = 80, buff = { "Cannot be Stunned" }, },
	req = { level = 27, },
}
itemBases["Thawing Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you become Frozen",
	implicitModTypes = { },
	charm = { duration = 2.2, chargesUsed = 80, chargesMax = 80, buff = { "Grants Immunity to Freeze" }, },
	req = { level = 12, },
}
itemBases["Topaz Charm"] = {
	type = "Charm",
	tags = { charm = true, default = true, },
	implicit = "Used when you take Lightning Damage from a Hit",
	implicitModTypes = { },
	charm = { duration = 4, chargesUsed = 40, chargesMax = 60, buff = { "+25% to Lightning Resistance" }, },
	req = { level = 5, },
}

