-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Broadhead Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "Adds 1 to 3 Physical Damage to Attacks",
	implicitIds = { "QuiverImplicitPhysicalDamage1" },
	implicitModTypes = { { "physical_damage", "damage", "physical", "attack" }, },
	req = { },
}
itemBases["Fire Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "Adds 3 to 5 Fire damage to Attacks",
	implicitIds = { "QuiverImplicitFireDamage1" },
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire", "attack" }, },
	req = { level = 8, },
}
itemBases["Sacral Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "Gain (2-3) Life per Enemy Hit with Attacks",
	implicitIds = { "QuiverImplicitLifeGainPerTarget1" },
	implicitModTypes = { { "resource", "life", "attack" }, },
	req = { level = 16, },
}
itemBases["Two-Point Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(20-30)% increased Accuracy Rating",
	implicitIds = { "QuiverImplicitIncreasedAccuracy1" },
	implicitModTypes = { { "attack" }, },
	req = { level = 24, },
}
itemBases["Blunt Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(25-40)% increased Stun Buildup",
	implicitIds = { "QuiverImplicitStunThresholdReduction1" },
	implicitModTypes = { {  }, },
	req = { level = 32, },
}
itemBases["Toxic Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(20-30)% chance to Poison on Hit with Attacks",
	implicitIds = { "QuiverImplicitChanceToPoison1" },
	implicitModTypes = { { "poison", "chaos", "attack", "ailment" }, },
	req = { level = 39, },
}
itemBases["Serrated Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "Attacks have (20-30)% chance to cause Bleeding",
	implicitIds = { "QuiverImplicitChanceToBleed1" },
	implicitModTypes = { { "bleed", "physical", "attack", "ailment" }, },
	req = { level = 44, },
}
itemBases["Primed Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(7-10)% increased Attack Speed",
	implicitIds = { "QuiverImplicitIncreasedAttackSpeed1" },
	implicitModTypes = { { "attack", "speed" }, },
	req = { level = 51, },
}
itemBases["Penetrating Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "100% chance to Pierce an Enemy",
	implicitIds = { "QuiverImplicitArrowAdditionalPierce1" },
	implicitModTypes = { {  }, },
	req = { level = 55, },
}
itemBases["Volant Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(20-30)% increased Arrow Speed",
	implicitIds = { "QuiverImplicitArrowSpeed1" },
	implicitModTypes = { { "attack", "speed" }, },
	req = { level = 60, },
}
itemBases["Visceral Quiver"] = {
	type = "Quiver",
	tags = { default = true, quiver = true, },
	implicit = "(20-30)% increased Critical Hit Chance for Attacks",
	implicitIds = { "QuiverImplicitCriticalStrikeChance1" },
	implicitModTypes = { { "attack", "critical" }, },
	req = { level = 64, },
}
