-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Body Rune"] = {
	type = "Rune",
	tags = { rune = true, default = true, },
	implicit = "Martial Weapons: Leeches 3% of Physical Damage as Life\nArmour: +25 to maximum Life",
	implicitModTypes = { },
	rune = { },
	req = { },
}
itemBases["Desert Rune"] = {
	type = "Rune",
	tags = { rune = true, default = true, },
	implicit = "Martial Weapons: Adds 7 to 11 Fire Damage\nArmour: +12% to Fire Resistance",
	implicitModTypes = { },
	rune = { },
	req = { },
}
itemBases["Glacial Rune"] = {
	type = "Rune",
	tags = { rune = true, default = true, },
	implicit = "Martial Weapons: Adds 6 to 10 Cold Damage\nArmour: +12% to Cold Resistance",
	implicitModTypes = { },
	rune = { },
	req = { },
}
itemBases["Mind Rune"] = {
	type = "Rune",
	tags = { rune = true, default = true, },
	implicit = "Martial Weapons: Leeches 2% of Physical Damage as Mana\nArmour: +20 to maximum Mana",
	implicitModTypes = { },
	rune = { },
	req = { },
}