-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Soul Core of Azcapa"] = {
	type = "Soul Core",
	tags = { soulcore = true, default = true, },
	implicit = "Martial Weapons: +15 to Spirit\nArmour: 10% increased Rarity of Items Found",
	implicitModTypes = { },
	soulcore = { },
	req = { },
}