-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Soul Core of Tacati"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 15% chance to Poison on Hit\nArmour: +7% to Chaos Resistance",
	req = { },
}
itemBases["Soul Core of Opiloti"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 15% chance to cause Bleeding on Hit\nArmour: 10% increased Charm Charges gained",
	req = { },
}
itemBases["Soul Core of Jiquani"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Recover 2% of Life on Kill\nArmour: 2% increased maximum Life",
	req = { },
}
itemBases["Soul Core of Zalatl"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Recover 2% of Mana on Kill\nArmour: 2% increased maximum Mana",
	req = { },
}
itemBases["Soul Core of Citaqualotl"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased Elemental Damage with Attacks\nArmour: +5% to all Elemental Resistances",
	req = { },
}
itemBases["Soul Core of Puhuarte"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased chance to Ignite\nArmour: +1% to Maximum Fire Resistance",
	req = { },
}
itemBases["Soul Core of Tzamoto"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 20% increased Freeze Buildup\nArmour: +1% to Maximum Cold Resistance",
	req = { },
}
itemBases["Soul Core of Xopec"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 30% increased chance to Shock\nArmour: +1% to Maximum Lightning Resistance",
	req = { },
}
itemBases["Soul Core of Azcapa"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +15 to Spirit\nArmour: 10% increased Rarity of Items found",
	req = { },
}
itemBases["Soul Core of Topotante"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Attacks with this Weapon Penetrate 15% Elemental Resistances\nArmour: 15% increased Elemental Ailment Threshold",
	req = { },
}
itemBases["Soul Core of Quipolatl"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 5% increased Attack Speed\nArmour: 10% reduced Slowing Potency of Debuffs on You",
	req = { },
}
itemBases["Soul Core of Ticaba"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +12% to Critical Damage Bonus\nArmour: Hits against you have 10% reduced Critical Damage Bonus",
	req = { },
}
itemBases["Soul Core of Atmohua"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Strength\nArmour: Convert 20% of Requirements to Strength",
	req = { },
}
itemBases["Soul Core of Cholotl"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Dexterity\nArmour: Convert 20% of Requirements to Dexterity",
	req = { },
}
itemBases["Soul Core of Zantipi"] = {
	type = "SoulCore",
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Convert 20% of Requirements to Intelligence\nArmour: Convert 20% of Requirements to Intelligence",
	req = { },
}

itemBases["Desert Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 7 to 11 Fire Damage\nArmour: +12% to Fire Resistance",
	req = { },
}
itemBases["Glacial Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 6 to 10 Cold Damage\nArmour: +12% to Cold Resistance",
	req = { },
}
itemBases["Storm Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Adds 1 to 20 Lightning Damage\nArmour: +12% to Lightning Resistance",
	req = { },
}
itemBases["Iron Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: 20% increased Physical Damage\nArmour: 20% increased Armour, Evasion and Energy Shield",
	req = { },
}
itemBases["Body Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 3% of Physical Damage as Life\nArmour: +25 to maximum Life",
	req = { },
}
itemBases["Mind Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Leeches 2% of Physical Damage as Mana\nArmour: +20 to maximum Mana",
	req = { },
}
itemBases["Rebirth Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 20 Life per Enemy Killed\nArmour: Regenerate 0.3% of Life per second",
	req = { },
}
itemBases["Inspiration Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Gain 10 Mana per Enemy Killed\nArmour: 15% increased Mana Regeneration Rate",
	req = { },
}
itemBases["Stone Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: Causes 25% increased Stun Buildup\nArmour: +40 to Stun Threshold",
	req = { },
}
itemBases["Vision Rune"] = {
	type = "Rune",
	tags = { default = true, },
	implicitModTypes = { },
	implicit = "Martial Weapons: +100 to Accuracy Rating\nArmour: 10% increased Life and Mana Recovery from Flasks",
	req = { },
}
