-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Clay Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Clamping Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Shrapnel Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Urn Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Incense Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicit = "(20-30)% increased Cooldown Recovery Rate for throwing Traps",
	implicitIds = { "TrapImplicitCooldownRecovery1", },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Bladed Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Dart Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Spike Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Coiled Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Lead Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Medallion Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Intricate Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
itemBases["Refined Trap"] = {
	type = "TrapTool",
	quality = 20,
	tags = { default = true, trap = true, twohand = true, },
	implicitIds = { },
	implicitModTypes = { },
	req = { },
}
