-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Buff data (c) Grinding Gear Games
--
local buffs, mod, flag = ...

buffs["archon_elemental"] = {
	name = "Elemental Archon",
	check="Condition:CanHaveElementalArchon",
	condition="ElementalArchon",
	stats={
		"elemental_damage_with_spell_skills_+%_final_from_archon_buff",
		"base_movement_velocity_+%",
		"base_resist_all_elements_%",
		"archon_spells_ignite_chance_+%_final",
		"archon_spells_hit_damage_freeze_multiplier_+%_final",
		"archon_spells_shock_chance_+%_final",
		"base_critical_strike_multiplier_+",
		"critical_strike_chance_+%",
	},
	flags={
		"have_archon_elemental",
		"deal_no_non_elemental_spell_damage",
		"base_is_floating",
	},
	grants={
		"elemental_damage_with_spell_skills_+%_final_from_archon_buff",
		"base_movement_velocity_+%",
		"base_resist_all_elements_%",
		"archon_spells_ignite_chance_+%_final",
		"archon_spells_hit_damage_freeze_multiplier_+%_final",
		"archon_spells_shock_chance_+%_final",
		"base_critical_strike_multiplier_+",
		"critical_strike_chance_+%",
	},
	values={
		{"buff_impl_stat",25},
		{"archon_grants_movement_speed_+%",0},
		{"archon_grants_all_elemental_resistance_+%",0},
		{"buff_impl_stat",100},
		{"buff_impl_stat",100},
		{"buff_impl_stat",100},
		{"archon_grants_base_critical_strike_multiplier_+",0},
		{"archon_grants_critical_strike_chance_+%",0},
	},
	duration = 10,
}