// emit_lua.mjs — turn the datamined JSON (item_bases, item_classes, skill_text,
// unique_names, stat_lines) into a single Lua data module the PoB fork loads at
// runtime: src/Data/ChineseTranslation.lua. Run under WSL node *after* the
// extract_*.mjs scripts:
//   node emit_lua.mjs
//
// Output table shape (returned by the module):
//   { bases = { [zh]=en, ... }, classes = { [zh]=en, ... },
//     skills = { [zh]=en, ... }, uniques = { [zh]=en, ... },
//     statLines = { { zhTemplate, enTemplate }, ... } }
// Labels / rarity words / state-flags are hand-mapped in the Lua translator
// itself (small, stable, and exact), so they are NOT emitted here.

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(HERE, 'data');
const OUT = path.resolve(HERE, '..', '..', 'src', 'Data', 'ChineseTranslation.lua');

const readJson = async (f) => JSON.parse(await fs.readFile(path.join(DATA, f), 'utf8'));

// Escape a JS string into a Lua double-quoted string literal. Lua strings are
// byte strings, so UTF-8 bytes pass through unchanged; we only escape the chars
// that would break a "..." literal.
function luaStr(s) {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    const code = s.charCodeAt(i);
    if (c === '\\') out += '\\\\';
    else if (c === '"') out += '\\"';
    else if (c === '\n') out += '\\n';
    else if (c === '\r') out += '\\r';
    else if (c === '\t') out += '\\t';
    else if (code < 32) out += '\\' + code;            // other control chars
    else out += c;
  }
  return out + '"';
}

// Emit a [zh]=en map, skipping no-op (zh===en) and blank entries; first zh wins.
function emitMap(name, pairs, lines) {
  const seen = new Set();
  lines.push(`d.${name} = {`);
  let n = 0;
  for (const [zh, en] of pairs) {
    if (!zh || !en || zh === en || seen.has(zh)) continue;
    seen.add(zh);
    lines.push(`  [${luaStr(zh)}]=${luaStr(en)},`);
    n++;
  }
  lines.push(`}`);
  return n;
}

async function main() {
  const bases = await readJson('item_bases.json');     // [{id,en,zh}]
  const classes = await readJson('item_classes.json'); // [{id,en,zh}]
  const skills = await readJson('skill_text.json');    // [{id,en_name,zh_name,...}]
  const uniques = await readJson('unique_names.json'); // [[zh,en], ...]
  const passives = await readJson('passive_names.json'); // [{id,en,zh}]
  const affixes = await readJson('mod_names.json');     // [{id,en,zh}] affix display names
  const statLines = await readJson('stat_lines.json'); // [[zh,en], ...]
  const clientStrings = await readJson('client_strings.json'); // [{id,en,zh}]

  const lines = [];
  lines.push('-- AUTO-GENERATED by tools/cn-translate/emit_lua.mjs — do not edit by hand.');
  lines.push('-- Source: datamined 国服 (WeGame) PoE2 client, en<->zh joined on metadata Id.');
  lines.push('-- Regenerate after a 国服 patch (see POB-FORK-HANDOFF.md).');
  lines.push('local d = { }');

  const nBases = emitMap('bases', bases.map(r => [r.zh, r.en]), lines);
  const nClasses = emitMap('classes', classes.map(r => [r.zh, r.en]), lines);
  const nSkills = emitMap('skills', skills.map(r => [r.zh_name, r.en_name]), lines);
  const nUniques = emitMap('uniques', uniques, lines);
  const nPassives = emitMap('passives', passives.map(r => [r.zh, r.en]), lines);
  const nAffixes = emitMap('affixes', affixes.map(r => [r.zh, r.en]), lines);

  // statLines as an ordered array of {zh, en} pairs (first-wins dedup already
  // done by extract_statdesc.mjs; we keep order so priority is preserved).
  lines.push('d.statLines = {');
  let nStat = 0;
  const seenStat = new Set();
  for (const pair of statLines) {
    const zh = pair[0], en = pair[1];
    if (!zh || !en || zh === en || seenStat.has(zh)) continue;
    seenStat.add(zh);
    lines.push(`  {${luaStr(zh)},${luaStr(en)}},`);
    nStat++;
  }
  lines.push('}');

  // propLines: item-text PROPERTY templates that render from ClientStrings (not
  // StatDescriptions) and appear in flask/charm/talisman pastes — flask recovery,
  // buff duration, charge lines. Same {N} placeholder format, so the translator
  // feeds them through the same matcher. Curated by Id prefix to avoid unrelated UI.
  const PROP_IDS = /^ItemDisplay(Flask|Charges|TalismanTier)/;
  lines.push('d.propLines = {');
  let nProp = 0;
  const seenProp = new Set();
  for (const r of clientStrings) {
    if (!PROP_IDS.test(r.id)) continue;
    // Chinese has no plural, so the "1Second"/"1Charge" singular templates share the
    // same zh as the "NSeconds"/"NCharges" plural ones; prefer the plural wording.
    if (/1(Second|Charge)$/.test(r.id)) continue;
    if (!r.zh || !r.en || r.zh === r.en || !/\{\d*\}/.test(r.en) || seenProp.has(r.zh)) continue;
    seenProp.add(r.zh);
    lines.push(`  {${luaStr(r.zh)},${luaStr(r.en)}},`);
    nProp++;
  }
  lines.push('}');
  lines.push('return d');

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, lines.join('\n') + '\n', 'utf8');
  const bytes = (await fs.stat(OUT)).size;
  console.log(`[emit_lua] wrote ${OUT}`);
  console.log(`[emit_lua] bases=${nBases} classes=${nClasses} skills=${nSkills} uniques=${nUniques} passives=${nPassives} affixes=${nAffixes} statLines=${nStat} propLines=${nProp} (${(bytes / 1048576).toFixed(2)} MB)`);
}
main().catch(e => { console.error('[emit_lua] ERROR:', e); process.exit(1); });
