-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Other active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["MeleeUnarmedPlayer"] = {
	name = "Punch",
	hidden = true,
	color = 4,
	incrementalEffectiveness = 0.054999999701977,
	description = "Perform an Unarmed Strike.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.Area] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	constantStats = {
		{ "melee_conditional_step_distance", 10 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { levelRequirement = 0, },
		[2] = { levelRequirement = 3, },
		[3] = { levelRequirement = 6, },
		[4] = { levelRequirement = 10, },
		[5] = { levelRequirement = 14, },
		[6] = { levelRequirement = 18, },
		[7] = { levelRequirement = 22, },
		[8] = { levelRequirement = 26, },
		[9] = { levelRequirement = 31, },
		[10] = { levelRequirement = 36, },
		[11] = { levelRequirement = 41, },
		[12] = { levelRequirement = 46, },
		[13] = { levelRequirement = 52, },
		[14] = { levelRequirement = 58, },
		[15] = { levelRequirement = 64, },
		[16] = { levelRequirement = 66, },
		[17] = { levelRequirement = 72, },
		[18] = { levelRequirement = 78, },
		[19] = { levelRequirement = 84, },
		[20] = { levelRequirement = 90, },
		[21] = { levelRequirement = 92, },
		[22] = { levelRequirement = 94, },
		[23] = { levelRequirement = 96, },
		[24] = { levelRequirement = 98, },
		[25] = { levelRequirement = 100, },
		[26] = { levelRequirement = 102, },
		[27] = { levelRequirement = 104, },
		[28] = { levelRequirement = 106, },
		[29] = { levelRequirement = 108, },
		[30] = { levelRequirement = 110, },
		[31] = { levelRequirement = 112, },
		[32] = { levelRequirement = 114, },
		[33] = { levelRequirement = 116, },
		[34] = { levelRequirement = 118, },
		[35] = { levelRequirement = 120, },
		[36] = { levelRequirement = 122, },
		[37] = { levelRequirement = 124, },
		[38] = { levelRequirement = 126, },
		[39] = { levelRequirement = 128, },
		[40] = { levelRequirement = 130, },
	},
}