-- This file is automatically generated, do not edit!
-- Flavour text data (c) Grinding Gear Games

return {
	[1] = {
		baseType = "FourUniqueBodyStr1",
		text = "It is safer to be feared than to be loved.",
		name = "Bramblejack",
	},
	[2] = {
		baseType = "FourUniqueBodyStr2",
		text = "An Ezomyte endures.",
		name = "Blackbraid",
	},
	[3] = {
		baseType = "FourUniqueBodyStr3",
		text = "In death, the legendary boar's tusks were turned\nto the slaying of Phaaryl's Eternal oppressors.",
		name = "Edyrn's Tusks",
	},
	[4] = {
		baseType = "FourUniqueBodyStr4",
		text = "That most legendary caravan bandit had\none rule: never let them see you flinch.",
		name = "The Road Warrior",
	},
	[5] = {
		baseType = "FourUniqueBodyStr5",
		text = "Not the sound of thunder on the wind, but the\nrhoaback riders—death charging from the sands.",
		name = "Titanrot Cataphract",
	},
	[6] = {
		baseType = "FourUniqueBodyStr6",
		text = "Knowing she could outlast any opponent,\nWrashmin fought not to win, but to delay.",
		name = "Wandering Reliquary",
	},
	[7] = {
		baseType = "FourUniqueBodyStr7",
		text = "The toughest armour is the trust of your people.",
		name = "Kingsguard",
	},
	[8] = {
		baseType = "FourUniqueBodyStr8",
		text = "Some would question if the risk was worth it.\nThe rest were already dead.",
		name = "Greed's Embrace",
	},
	[9] = {
		baseType = "FourUniqueBodyStr12_",
		text = "The turtle's shell one day becomes its tomb.",
		name = "The Brass Dome",
	},
	[10] = {
		baseType = "FourUniqueBodyStr14",
		text = "The warrior who fears will fall.",
		name = "Kaom's Heart",
	},
	[11] = {
		baseType = "FourUniqueBodyDex1",
		text = "When cornered and desperate, look within for the rage to break loose.",
		name = "Bristleboar",
	},
	[12] = {
		baseType = "FourUniqueBodyDex2",
		text = "To catch an animal, think like an animal.",
		name = "Foxshade",
	},
	[13] = {
		baseType = "FourUniqueBodyDex3",
		text = "The blasted oak stands forever.",
		name = "Ashrend",
	},
	[14] = {
		baseType = "FourUniqueBodyDex4",
		text = "The desert is ever flowing.",
		name = "Sands of Silk",
	},
	[15] = {
		baseType = "FourUniqueBodyDex5",
		text = "\"I carry neither food nor drink. I rely on the charity\nof my fellow wayfarers. Dead men are generous men.\"\n- Taruk of the Wildmen",
		name = "Briskwrap",
	},
	[16] = {
		baseType = "FourUniqueBodyDex6",
		text = "Wraeclast has suffered many great disasters,\nbut life always springs back anew.",
		name = "Dustbloom",
	},
	[17] = {
		baseType = "FourUniqueBodyDex7",
		text = "The truth lies inside every man, if you dig around.\nMany a confession was found in the bowels of Axiom.",
		name = "The Rat Cage",
	},
	[18] = {
		baseType = "FourUniqueBodyDex8",
		text = "As the serpent wills.",
		name = "Quatl's Molt",
	},
	[19] = {
		baseType = "FourUniqueBodyDex10",
		text = "Shedding away her regal past,\nshe forged a new destiny.\nSacrificing the ephemeral joys of man,\nshe embraced the eternal grasp of nature.\nSeizing her one true wish,\nshe found peace at last.",
		name = "Queen of the Forest",
	},
	[20] = {
		baseType = "FourUniqueBodyDex11",
		text = "Feed a beast and it will not hunt.\nProtect it and it will not fight.\nFerocity must be learned, not taught.\nIt is suffering that forges the greatest warriors.",
		name = "Yriel's Fostering",
	},
	[21] = {
		baseType = "FourUniqueBodyDex15",
		text = "Hyrri loosed a barrage of arrows,\ntipped with a poisoned hatred\nonly oppression can ferment.",
		name = "Hyrri's Ire",
	},
	[22] = {
		baseType = "FourUniqueBodyInt1",
		text = "Faith springs abundant at the edge of death.",
		name = "Ghostwrithe",
	},
	[23] = {
		baseType = "FourUniqueBodyInt2",
		text = "The soul cannot flourish in a doubting mind.",
		name = "Bitterbloom",
	},
	[24] = {
		baseType = "FourUniqueBodyInt3",
		text = "Suspicion is a sinister shadow slithering in the soul.",
		name = "The Black Doubt",
	},
	[25] = {
		baseType = "FourUniqueBodyInt4",
		text = "Fueled by the blackness in the hearts of men,\nthe armies of Saresh were just as relentless.",
		name = "Necromantle",
	},
	[26] = {
		baseType = "FourUniqueBodyInt5",
		text = "He who sows an ember shall reap an inferno.",
		name = "Cloak of Flame",
	},
	[27] = {
		baseType = "FourUniqueBodyInt6",
		text = "In its final era, the roofs of Keth were rife with\nanything and everything that could hold water...\nshould the opportunity arise.",
		name = "Prayers for Rain",
	},
	[28] = {
		baseType = "FourUniqueBodyInt7",
		text = "A faith born of flesh.",
		name = "Tetzlapokal's Desire",
	},
	[29] = {
		baseType = "FourUniqueBodyInt8",
		text = "My Soul is your Strength\nMy Price is your Blood",
		name = "The Covenant",
	},
	[30] = {
		baseType = "FourUniqueBodyInt9",
		text = "The tale-women of old knew how to build anticipation.",
		name = "Gloamgown",
	},
	[31] = {
		baseType = "FourUniqueBodyInt12",
		text = "Reap what others have sown\nMuster them from their graves\nParade them for your pleasure\nZealots in mortis enslaved",
		name = "Vis Mortis",
	},
	[32] = {
		baseType = "FourUniqueBodyInt13",
		text = "When the throat roars,\nAs eyes weep,\nWhen the hand grips hard\nWith trembling fingers,\nWhen belly twists\nYet legs stand strong,\nThat is the work\nOf the Defiant Heart.",
		name = "Cloak of Defiance",
	},
	[33] = {
		baseType = "FourUniqueBodyInt14",
		text = "Hallowed Dordalus was cast into the pit as a heretic,\nbut his piety was so great, he would not burn.\nHe rose again, lauded, his faith forever changed...\nbut not the way the Templar believed.",
		name = "Silks of Veneration",
	},
	[34] = {
		baseType = "FourUniqueBodyStrDex1",
		text = "For those noble families obsessed\nwith keeping their bloodline pure,\nthere was a price to pay...",
		name = "Coat of Red",
	},
	[35] = {
		baseType = "FourUniqueBodyStrDex2",
		text = "In the mists they dwell,\nforever hungry,\nforever cold.",
		name = "The Barrow Dweller",
	},
	[36] = {
		baseType = "FourUniqueBodyStrDex3",
		text = "A power unknown aids your own.",
		name = "Irongrasp",
	},
	[37] = {
		baseType = "FourUniqueBodyStrDex4",
		text = "His isolation caused him to treasure\ntheir companionship all the more.",
		name = "Pariah's Embrace",
	},
	[38] = {
		baseType = "FourUniqueBodyStrDex5",
		text = "There is no safer place\nThan the Belly of the Beast",
		name = "Belly of the Beast",
	},
	[39] = {
		baseType = "FourUniqueBodyStrDex6",
		text = "\"This was the first step in some grand design,\nlost to the ages, now ours to decipher.\"\n- Dominus, High Templar",
		name = "Doryani's Prototype",
	},
	[40] = {
		baseType = "FourUniqueBodyStrDex7",
		text = "That day, both the Unblinking Eye and\ntheir enemies stood in silence. That day,\nthe sky was clear, but it was raining.",
		name = "Widow's Reign",
	},
	[41] = {
		baseType = "FourUniqueBodyStrDex9",
		text = "\"I will never forget. I will carry your memory\nforward, all of you, from this ghastly Vale.\"\n- Artair, last survivor of the Ogham rebellion",
		name = "The Fallen Formation",
	},
	[42] = {
		baseType = "FourUniqueBodyStrDex11",
		text = "Whiff of cold, tiny spark, faintest flicker in the dark.\nEmbers swirl, ice takes form, sky exposed - Death's perfect storm.\nFrost and thunder, flames shine bright, ruin walks the land tonight.\nBy your hand they dance and bend, wield them and brook no end.",
		name = "The Coming Calamity",
	},
	[43] = {
		baseType = "FourUniqueBodyStrInt1_",
		text = "The gleam of the night and howling teeth alike could not abate the rising of the sun.",
		name = "Enfolding Dawn",
	},
	[44] = {
		baseType = "FourUniqueBodyStrInt3",
		text = "When Solaris closes her burning eye\nAt the end of time,\nthe world will perish in ice.",
		name = "Icetomb",
	},
	[45] = {
		baseType = "FourUniqueBodyStrInt4",
		text = "Yes... but what if?",
		name = "Husk of Dreams",
	},
	[46] = {
		baseType = "FourUniqueBodyStrInt5",
		text = "Although a great leader during the war,\nVoll proved disastrous in times of peace.",
		name = "Voll's Protector",
	},
	[47] = {
		baseType = "FourUniqueBodyStrInt6",
		text = "The greatest mistakes cause suffering\nlong after they have been made",
		name = "Soul Mantle",
	},
	[48] = {
		baseType = "FourUniqueBodyStrInt7",
		text = "Through every great purge, and every fiery inquisition,\nthe Twilight Order endured in secret.",
		name = "The Mutable Star",
	},
	[49] = {
		baseType = "FourUniqueBodyStrInt8",
		text = "\"Move in ways your enemy does not expect.\nConfuse them with elegance and grace.\nThey'll never see the axe coming.\"\n- Rakiata, Chieftain of the Tasalio Tribe",
		name = "Waveshaper",
	},
	[50] = {
		baseType = "FourUniqueBodyStrInt9",
		text = "It is often said of nobles that they live off their\npeasants... sometimes, it's truer than any suspect.",
		name = "Couture of Crimson",
	},
	[51] = {
		baseType = "FourUniqueBodyStrInt12",
		text = "The Twilight Order rejected the gods, choosing\ninstead to put their faith in each other.",
		name = "Sacrosanctum",
	},
	[52] = {
		baseType = "FourUniqueBodyDexInt1",
		text = "\"Prepare the rack, boy. And be careful with those hooks!\"\n- the Master Torturer's last words",
		name = "Apron of Emiran",
	},
	[53] = {
		baseType = "FourUniqueBodyDexInt2",
		text = "It was in this forsaken land, where mists shroud the world in mystery,\nthat thieves, murderers, and outcasts, sought refuge.",
		name = "Gloomform",
	},
	[54] = {
		baseType = "FourUniqueBodyDexInt3",
		text = "Born among the high peaks, many Mutewind\nlive their entire lives in snow and ice.",
		name = "Sierran Inheritance",
	},
	[55] = {
		baseType = "FourUniqueBodyDexInt4",
		text = "Be not where death falls.",
		name = "The Dancing Mirage",
	},
	[56] = {
		baseType = "FourUniqueBodyDexInt5",
		text = "In all things, control.",
		name = "Redflare Conduit",
	},
	[57] = {
		baseType = "FourUniqueBodyDexInt6",
		text = "Mortality is a curse.\nThe cure is simple.",
		name = "Zerphi's Serape",
	},
	[58] = {
		baseType = "FourUniqueBodyStrDexInt1",
		text = "",
		name = "Tabula Rasa",
	},
	[59] = {
		baseType = "FourUniqueHelmetStr1a",
		text = "The younger brother waded into battle, shrugging off blows.",
		name = "Horns of Bynden",
	},
	[60] = {
		baseType = "FourUniqueHelmetStr1b",
		text = "The older brother retained calm in the midst of fury.",
		name = "Wings of Caelyn",
	},
	[61] = {
		baseType = "FourUniqueHelmetStr2",
		text = "Centuries of servitude, a day\nof glory, an eternity of death.",
		name = "Ezomyte Peak",
	},
	[62] = {
		baseType = "FourUniqueHelmetStr3",
		text = "The beasts we fear the most\nare the ones who dwell in total darkness.",
		name = "Black Sun Crest",
	},
	[63] = {
		baseType = "FourUniqueHelmetStr4",
		text = "We may fight, and we may die, but in these\nmoments of blood and battle, we truly live.",
		name = "Thrillsteel",
	},
	[64] = {
		baseType = "FourUniqueHelmetStr5",
		text = "May you never hear it toll.",
		name = "Deidbell",
	},
	[65] = {
		baseType = "FourUniqueHelmetStr6",
		text = "Only the High Priests could enact the sacrifices,\nbut all who witnessed shared in exultation.",
		name = "Corona of the Red Sun",
	},
	[66] = {
		baseType = "FourUniqueHelmetStr8",
		text = "An eye for an eye makes the whole world dead.",
		name = "Blood Price",
	},
	[67] = {
		baseType = "FourUniqueHelmetDex1",
		text = "Beyond madness lies inspiration.",
		name = "Innsmouth",
	},
	[68] = {
		baseType = "FourUniqueHelmetDex2",
		text = "No metal slips as easily through the fingers as gold.",
		name = "Goldrim",
	},
	[69] = {
		baseType = "FourUniqueHelmetDex3",
		text = "No man burns alone.",
		name = "Radiant Grief",
	},
	[70] = {
		baseType = "FourUniqueHelmetDex5",
		text = "Ancient worshippers of the Greatwolf were overtaken\nby a ravenous hunger for all things mystical.",
		name = "Elevore",
	},
	[71] = {
		baseType = "FourUniqueHelmetDex7",
		text = "Brinerot pirates live in a perpetual blaze of glory,\npushing their luck right to the end.",
		name = "The Black Insignia",
	},
	[72] = {
		baseType = "FourUniqueHelmetDex8",
		text = "There was no hero made out of Starkonja's death,\nbut merely a long sleep made eternal.",
		name = "Starkonja's Head",
	},
	[73] = {
		baseType = "FourUniqueHelmetDex9",
		text = "Give of your heated passions.\nGive of your cold resolve.\nYou will be repaid.",
		name = "Heatshiver",
	},
	[74] = {
		baseType = "FourUniqueHelmetDex10",
		text = "The end always comes sooner than we think.",
		name = "Myris Uxor",
	},
	[75] = {
		baseType = "FourUniqueHelmetDex11",
		text = "Nature respects the strong\nAnd paints the snow red\nWith the blood of the weak",
		name = "Alpha's Howl",
	},
	[76] = {
		baseType = "FourUniqueHelmetInt1",
		text = "Lift it lightly, don it slow.\nThe spikes point out and in, you know.",
		name = "Crown of Thorns",
	},
	[77] = {
		baseType = "FourUniqueHelmetInt2",
		text = "The spirit hungers for the flesh.",
		name = "The Devouring Diadem",
	},
	[78] = {
		baseType = "FourUniqueHelmetInt3",
		text = "Tale-women do not fight as dekharas.\nThey command a power all their own.",
		name = "Visage of Ayah",
	},
	[79] = {
		baseType = "FourUniqueHelmetInt4",
		text = "Keep your heart as ice,\nlest your passions stir.",
		name = "Forbidden Gaze",
	},
	[80] = {
		baseType = "FourUniqueHelmetInt5",
		text = "From the flesh of the gods, Xibaqua was born.\nFrom the carnage of Xibaqua, we were born.\nIt is our duty to return to the gods what was once theirs.",
		name = "Mask of the Stitched Demon",
	},
	[81] = {
		baseType = "FourUniqueHelmetInt6",
		text = "They screamed her name in adulation as they gave\ntheir very lives. She looked on with impatience.",
		name = "Atziri's Disdain",
	},
	[82] = {
		baseType = "FourUniqueHelmetInt7",
		text = "Turning, gazing, blinking,\nbehold the eyes of void.\nBurning, razing, drinking,\nyour mind is destroyed.",
		name = "Crown of Eyes",
	},
	[83] = {
		baseType = "FourUniqueHelmetInt8",
		text = "\"The sharper the pain, the sharper the mind.\nA curious paradox.\"\n- Shavronne of Umbra",
		name = "Scold's Bridle",
	},
	[84] = {
		baseType = "FourUniqueHelmetInt11",
		text = "Where the body's limits begin,\nthe mind's limits end.",
		name = "Indigon",
	},
	[85] = {
		baseType = "FourUniqueHelmetStrDex1",
		text = "In the end, even heroes fade away.",
		name = "Greymake",
	},
	[86] = {
		baseType = "FourUniqueHelmetStrDex2",
		text = "Sometimes patching up your\nequipment gets out of hand.",
		name = "Erian's Cobble",
	},
	[87] = {
		baseType = "FourUniqueHelmetStrDex3",
		text = "Let the rider's aim be true.",
		name = "Ironride",
	},
	[88] = {
		baseType = "FourUniqueHelmetStrDex4",
		text = "He never spoke a word. His opponents imagined\ntheir own personal mockeries, most cruel.",
		name = "The Smiling Knight",
	},
	[89] = {
		baseType = "FourUniqueHelmetStrDex5",
		text = "Familiarity breeds contempt.",
		name = "The Vile Knight",
	},
	[90] = {
		baseType = "FourUniqueHelmetStrDex7",
		text = "\"What lies beneath your feet?!\"\n\"Sacred ground, watered with tears of blood!\"",
		name = "The Bringer of Rain",
	},
	[91] = {
		baseType = "FourUniqueHelmetStrInt1",
		text = "An endless river of bodies lie in the wake of ambition.",
		name = "Crown of the Victor",
	},
	[92] = {
		baseType = "FourUniqueHelmetStrInt2",
		text = "Heavy is the head.",
		name = "Bronzebeard",
	},
	[93] = {
		baseType = "FourUniqueHelmetStrInt3",
		text = "A lightless world\na silent reign\ntwo sightless eyes\nfeed on your pain.",
		name = "Crown of the Pale King",
	},
	[94] = {
		baseType = "FourUniqueHelmetStrInt4",
		text = "The seeds of greatness are planted in darkness,\nWatered by suffering,\nTended by desperation,\nAnd bloom steel flowers of victory.",
		name = "Veil of the Night",
	},
	[95] = {
		baseType = "FourUniqueHelmetStrInt5",
		text = "Pain brings clarity.",
		name = "Cornathaum",
	},
	[96] = {
		baseType = "FourUniqueHelmetStrInt6",
		text = "Death crawls in darkness, closer than we think.",
		name = "The Deepest Tower",
	},
	[97] = {
		baseType = "FourUniqueHelmetDexInt1",
		text = "The roots take hold within...",
		name = "The Hollow Mask",
	},
	[98] = {
		baseType = "FourUniqueHelmetDexInt2",
		text = "A terror of ancient times, his identity\nremains lost... but his power does not.",
		name = "Mask of the Sanguimancer",
	},
	[99] = {
		baseType = "FourUniqueHelmetDexInt3",
		text = "For none of us are as cruel as all of us.",
		name = "Leer Cast",
	},
	[100] = {
		baseType = "FourUniqueHelmetDexInt4",
		text = "Remaining unseen, the Dishonoured Assassin struck\nonly in the depths of the harshest sandstorms.",
		name = "Atsak's Sight",
	},
	[101] = {
		baseType = "FourUniqueHelmetDexInt5",
		text = "\"A queen should be seen, admired, but never touched.\"\n- Atziri, Queen of the Vaal",
		name = "The Vertex",
	},
	[102] = {
		baseType = "FourUniqueHelmetDexInt6",
		text = "\"The ice seared his naked feet\nAs the lightning stilled his heart,\nBut it was the flames upon his lover's face\nThat roused him to vengeance.\"\n- From 'The Three Dragons' by Victario of Sarn",
		name = "The Three Dragons",
	},
	[103] = {
		baseType = "FourUniqueGlovesStr2",
		text = "The largest beings on Wraeclast\nare not flesh and blood.",
		name = "Treefingers",
	},
	[104] = {
		baseType = "FourUniqueGlovesStr3",
		text = "Why cling to your sanity? It offers you nothing.\nSurrender to me, and I will grant you everything.",
		name = "Lochtonial Caress",
	},
	[105] = {
		baseType = "FourUniqueGlovesStr4",
		text = "What is worse, the sting of the past, the pain of the present, or the fear of the future?",
		name = "Dreadfist",
	},
	[106] = {
		baseType = "FourUniqueGlovesStr5",
		text = "\"The heart is the herald.\nIt will tell me when it is best to strike.\"\n- Atziri, Queen of the Vaal",
		name = "Atziri's Acuity",
	},
	[107] = {
		baseType = "FourUniqueGlovesStr7",
		text = "\"I like my vassals at sword point,\nbut my enemies as close as the hilt.\"\n- Emperor Chitus",
		name = "Empire's Grasp",
	},
	[108] = {
		baseType = "FourUniqueGlovesDex1_",
		text = "Fight with the ferocity of the First Ones.",
		name = "Northpaw",
	},
	[109] = {
		baseType = "FourUniqueGlovesDex2",
		text = "After the eruption, the skies turned grey,\nash began to fall, and a chill set in...",
		name = "Grip of Winter",
	},
	[110] = {
		baseType = "FourUniqueGlovesDex4",
		text = "The devil finds work for idle hands.",
		name = "Idle Hands",
	},
	[111] = {
		baseType = "FourUniqueGlovesDex5",
		text = "As the serpent shuns thought,\nIt shuns fear.\nIt strikes with the speed of wrath\nAnd the skill of compulsion.",
		name = "Snakebite",
	},
	[112] = {
		baseType = "FourUniqueGlovesDex6",
		text = "Maligaro operated effortlessly,\nwith great speed and terrible consequences.",
		name = "Maligaro's Virtuosity",
	},
	[113] = {
		baseType = "FourUniqueGlovesInt1",
		text = "Bloodshed on the crimson shores,\nlonging for the endless sea.\nTreasures, life, I'd give it all\njust to capture thee.",
		name = "Painter's Servant",
	},
	[114] = {
		baseType = "FourUniqueGlovesInt2",
		text = "You can be the wick or the wax. Either way, your light goes out and mine goes on.",
		name = "Candlemaker",
	},
	[115] = {
		baseType = "FourUniqueGlovesInt3",
		text = "While Doedre lacked Maligaro's sense of style,\nshe surpassed her master in pure malevolence.",
		name = "Doedre's Tenure",
	},
	[116] = {
		baseType = "FourUniqueGlovesInt4",
		text = "Reality is a puzzle. Ingenuity is power.",
		name = "Kitoko's Current",
	},
	[117] = {
		baseType = "FourUniqueGlovesInt5",
		text = "Xibaqua's treachery was met with divine fury.\nOne by one, the gods reclaimed their flesh,\nuntil all that remained was a droplet of pure light:\nThe first Vaal.",
		name = "Demon Stitcher",
	},
	[118] = {
		baseType = "FourUniqueGlovesInt6",
		text = "Diamora sings not for hunger, but for longing.",
		name = "Nightscale",
	},
	[119] = {
		baseType = "FourUniqueGlovesInt7",
		text = "\"Keep smiling. The deepest cut comes not from insults, but from false praise.\"",
		name = "Leopold's Applause",
	},
	[120] = {
		baseType = "FourUniqueGlovesStrDex1",
		text = "The whispers of the old gods hum through the iron. They demand a hero.",
		name = "Jarngreipr",
	},
	[121] = {
		baseType = "FourUniqueGlovesStrDex2",
		text = "Wealth is not to be borne lightly.",
		name = "Aurseize",
	},
	[122] = {
		baseType = "FourUniqueGlovesStrDex3",
		text = "Anticipation is a gift.",
		name = "Deathblow",
	},
	[123] = {
		baseType = "FourUniqueGlovesStrDex4",
		text = "Unlike the other gods, when he was born from the volcano,\nValako rode the clouds of ash into the thundering sky.",
		name = "Valako's Vice",
	},
	[124] = {
		baseType = "FourUniqueGlovesStrDex5",
		text = "The strongest souls are forged through struggle and defeat.",
		name = "Aerisvane's Wings",
	},
	[125] = {
		baseType = "FourUniqueGlovesStrInt1",
		text = "Try as you like to hide the\nblood on your hands.\nYou'll still know the truth.",
		name = "Gravebind",
	},
	[126] = {
		baseType = "FourUniqueGlovesStrInt2",
		text = "Captivity breeds creativity.",
		name = "Shackles of the Wretched",
	},
	[127] = {
		baseType = "FourUniqueGlovesStrInt3",
		text = "The secret was lost with its maker.",
		name = "Blueflame Bracers",
	},
	[128] = {
		baseType = "FourUniqueGlovesStrInt4",
		text = "Only once did Maligaro wonder if he'd gone too far.\nHis greatest success took three entire legions to capture.",
		name = "The Prisoner's Manacles",
	},
	[129] = {
		baseType = "FourUniqueGlovesDexInt1",
		text = "Ulcers, scabs, and pocks, the third army makes its claim.",
		name = "Plaguefinger",
	},
	[130] = {
		baseType = "FourUniqueGlovesDexInt2",
		text = "\"Stitches? Wouldn't that defeat the purpose?\"\n- Jeffry, Torturer's Apprentice",
		name = "Killjoy",
	},
	[131] = {
		baseType = "FourUniqueGlovesDexInt5",
		text = "The darkest clouds clashed and coupled,\ngiving birth to four lightning children of hate.",
		name = "Essentia Sanguis",
	},
	[132] = {
		baseType = "FourUniqueBootsStr1",
		text = "A wall of steel and muscle.",
		name = "Legionstride",
	},
	[133] = {
		baseType = "FourUniqueBootsStr2",
		text = "Natural decay can be twisted to dark ends.",
		name = "Corpsewade",
	},
	[134] = {
		baseType = "FourUniqueBootsStr3",
		text = "We move to be closer to her, but the distance yet grows.",
		name = "The Infinite Pursuit",
	},
	[135] = {
		baseType = "FourUniqueBootsStr4",
		text = "The truly mighty are never outnumbered.",
		name = "Trampletoe",
	},
	[136] = {
		baseType = "FourUniqueBootsStr5",
		text = "As the sun rises and the light approaches,\nso too shall your enemies fear you.",
		name = "Birth of Fury",
	},
	[137] = {
		baseType = "FourUniqueBootsDex2",
		text = "The druids walk the Grelwood without fear.",
		name = "Briarpatch",
	},
	[138] = {
		baseType = "FourUniqueBootsDex3",
		text = "All your tomorrows lie ahead of you,\nunknown and snarled to the very last.",
		name = "Gamblesprint",
	},
	[139] = {
		baseType = "FourUniqueBootsDex4",
		text = "Where legends tread,\nthe world hearkens.",
		name = "Thunderstep",
	},
	[140] = {
		baseType = "FourUniqueBootsDex5",
		text = "Banished for his tragic failure,\nErian learned to hunt to survive.",
		name = "Bushwhack",
	},
	[141] = {
		baseType = "FourUniqueBootsInt1",
		text = "Blessed are those who tend the Grove.",
		name = "Luminous Pace",
	},
	[142] = {
		baseType = "FourUniqueBootsInt2",
		text = "All the world is my home.",
		name = "Wanderlust",
	},
	[143] = {
		baseType = "FourUniqueBootsInt3",
		text = "The dead man walks where\nthe living fear to tread.",
		name = "Bones of Ullr",
	},
	[144] = {
		baseType = "FourUniqueBootsInt4",
		text = "Wonders abound at death's door.",
		name = "Wondertrap",
	},
	[145] = {
		baseType = "FourUniqueBootsInt5",
		text = "The mocking wind, a shielding spell,\nThe haunting screams, a maddening hell",
		name = "Windscream",
	},
	[146] = {
		baseType = "FourUniqueBootsStrDex1",
		text = "Some search forever for their path.",
		name = "The Knight-errant",
	},
	[147] = {
		baseType = "FourUniqueBootsStrDex2",
		text = "\"Sirrius flew on wings of light, faster than wind, faster\nthan thought. But try as he might to outrun the darkness,\nit was there, at every turn, waiting for him.\"\n- Azmerian legend",
		name = "Darkray Vectors",
	},
	[148] = {
		baseType = "FourUniqueBootsStrDex3",
		text = "The storm cannot sway those of sure footing.",
		name = "Obern's Bastion",
	},
	[149] = {
		baseType = "FourUniqueBootsStrInt2",
		text = "Tempest's power given form,\nFlee before the walking storm.",
		name = "Wake of Destruction",
	},
	[150] = {
		baseType = "FourUniqueBootsDexInt2",
		text = "The cursed ones march forever,\nOn their hopeless, last endeavour.",
		name = "Ghostmarch",
	},
	[151] = {
		baseType = "FourUniqueBootsDexInt3",
		text = "The combat stance used by Vaal nobles\nwas as elegant as it was deadly.",
		name = "Powertread",
	},
	[152] = {
		baseType = "FourUniqueShieldStr1",
		text = "Praetor Draven knew his only chance to subjugate\nthe Ezomytes was to catch them unaware.",
		name = "Dionadair",
	},
	[153] = {
		baseType = "FourUniqueShieldStr2",
		text = "The Counts of Ogham share a\nlegacy of cunning and power.",
		name = "Wulfsbane",
	},
	[154] = {
		baseType = "FourUniqueShieldStr3",
		text = "Welcome to Wraeclast.",
		name = "Doomgate",
	},
	[155] = {
		baseType = "FourUniqueShieldStr4",
		text = "\"Beyond fire, blood, and nightmare,\nthe Savior will build utopia.\"",
		name = "Window to Paradise",
	},
	[156] = {
		baseType = "FourUniqueShieldStr5",
		text = "Some stories are never told.",
		name = "The Wailing Wall",
	},
	[157] = {
		baseType = "FourUniqueShieldStr6",
		text = "A true predator does not chase; It waits.",
		name = "Lycosidae",
	},
	[158] = {
		baseType = "FourUniqueShieldStr7",
		text = "Blood shed is blood shared.",
		name = "Redblade Banner",
	},
	[159] = {
		baseType = "FourUniqueShieldStr8",
		text = "Our hearts cry out\nbut are silenced by our flesh\nand so we give up our flesh.",
		name = "The Surrender",
	},
	[160] = {
		baseType = "FourUniqueShieldStr13",
		text = "Fire dances with those who doubt\nLicks the skin and flesh from the fearful\nWhere there is no fear\nThere is no flame",
		name = "Chernobog's Pillar",
	},
	[161] = {
		baseType = "FourUniqueShieldStrDex1",
		text = "The unending carnage of war\nmercilessly grinds away\nat body and mind.",
		name = "Arvil's Wheel",
	},
	[162] = {
		baseType = "FourUniqueShieldStrDex2",
		text = "Lead by example, and you shall never be alone.",
		name = "Merit of Service",
	},
	[163] = {
		baseType = "FourUniqueShieldStrDex4",
		text = "Ride the western wind, and take flight.",
		name = "Feathered Fortress",
	},
	[164] = {
		baseType = "FourUniqueShieldStrInt1",
		text = "May your resolve never waver.",
		name = "Alkem Eira",
	},
	[165] = {
		baseType = "FourUniqueShieldStrInt2",
		text = "The druids swore to protect the Grelwood with their very lives.",
		name = "Oaksworn",
	},
	[166] = {
		baseType = "FourUniqueShieldStrInt3",
		text = "A swift mind solves problems before they occur.",
		name = "Saffell's Frame",
	},
	[167] = {
		baseType = "FourUniqueShieldStrInt4",
		text = "When the Red Sekhema called,\nthe Ardura were the first to answer.",
		name = "Crest of Ardura",
	},
	[168] = {
		baseType = "FourUniqueShieldStrInt5",
		text = "When blood is paid, the weak think twice.",
		name = "Prism Guardian",
	},
	[169] = {
		baseType = "FourUniqueShieldStrInt6",
		text = "My bearer shall be guarded by flame,\nfor I am the phoenix, forever radiant in glory.",
		name = "Rise of the Phoenix",
	},
	[170] = {
		baseType = "FourUniqueShieldDex1",
		text = "\"A thief in the night, Draven did creep,\nfamilies asleep, taken, held on high.\nClever, he thought, 'til his children paid.\nNay, villain, a man never bleeds alone.\"",
		name = "Dunkelhalt",
	},
	[171] = {
		baseType = "FourUniqueShieldDex2",
		text = "Light and shadow chase eternal,\nbut neither knows the other exists...",
		name = "Nocturne",
	},
	[172] = {
		baseType = "FourUniqueShieldDex3",
		text = "\"Resist for long enough, and your oppressor\nwill lose his will. Then, you've won.\"",
		name = "Rondel de Ezo",
	},
	[173] = {
		baseType = "FourUniqueShieldDex4",
		text = "A window onto a realm of red,\nwhere countless voices scream...",
		name = "Bloodbarrier",
	},
	[174] = {
		baseType = "FourUniqueShieldDex6",
		text = "As a boy, in the arena, Daresso learned to\nfeign weakness to open up a lethal blow.",
		name = "Silverthorne",
	},
	[175] = {
		baseType = "FourUniqueShieldDex11_",
		text = "\"There is nowhere my vengeance cannot find you.\"",
		name = "Calgyra's Arc",
	},
	[176] = {
		baseType = "FourUniqueShieldDex12",
		text = "\"Lundara held back the hordes, while Solerai rose to split the sky.\nWith a single stroke, she ended the Winter of the World.\"\n- Wranga, tale-woman of the Wahida akhara",
		name = "Sunsplinter",
	},
	[177] = {
		baseType = "FourUniqueFocus1",
		text = "The cry of death whispers in the wind.",
		name = "Deathrattle",
	},
	[178] = {
		baseType = "FourUniqueFocus2",
		text = "A gift, a braid, of golden hair.\nThe war, forgotten.\nThe reason, remembered.",
		name = "Threaded Light",
	},
	[179] = {
		baseType = "FourUniqueFocus3",
		text = "The horrors we imagined as children\nstill exist somewhere in the dark...",
		name = "Effigy of Cruelty",
	},
	[180] = {
		baseType = "FourUniqueFocus4",
		text = "Obedience stretches beyond the grave.",
		name = "Carrion Call",
	},
	[181] = {
		baseType = "FourUniqueFocus5",
		text = "Sinuous, entwined... inextricable.",
		name = "Serpent's Lesson",
	},
	[182] = {
		baseType = "FourUniqueFocus6",
		text = "A flash of blue, a stormcloud's kiss,\nher motionless dance the pulse of bliss",
		name = "The Eternal Spark",
	},
	[183] = {
		baseType = "FourUniqueFocus7",
		text = "Give him your body, and your burdens will follow.",
		name = "Apep's Supremacy",
	},
	[184] = {
		baseType = "FourUniqueFocus8",
		text = "The Vaal emptied their slaves of beating hearts,\nand left a mountain of twitching dead.",
		name = "Rathpith Globe",
	},
	[185] = {
		baseType = "FourUniqueQuiver1",
		text = "Mist of breath\nIcing to lips and throat\nAs the warm ones choke and fall\nUpon the frozen wasteland.",
		name = "Asphyxia's Wrath",
	},
	[186] = {
		baseType = "FourUniqueQuiver2_",
		text = "Molten feathers, veiled spark,\nHissing arrows from the dark.",
		name = "Blackgleam",
	},
	[187] = {
		baseType = "FourUniqueQuiver3",
		text = "Life and death ooze from the same sap.",
		name = "The Lethal Draw",
	},
	[188] = {
		baseType = "FourUniqueQuiver5",
		text = "\"It's a rare man that has eyes in the back of his head.\"\n- Kiravi, Vaal Archer",
		name = "Rearguard",
	},
	[189] = {
		baseType = "FourUniqueAmulet1",
		text = "A hearth unyielding, ever warm,\nA light unbroken, endlessly reborn.",
		name = "Igniferis",
	},
	[190] = {
		baseType = "FourUniqueAmulet2",
		text = "Worship of house gods was tolerated\nin Oriath, so long as it remained private.",
		name = "Idol of Uldurn",
	},
	[191] = {
		baseType = "FourUniqueAmulet3",
		text = "What they saw was what they believed, and\nthey believed Lunaris had not abandoned them.",
		name = "The Everlasting Gaze",
	},
	[192] = {
		baseType = "FourUniqueAmulet4",
		text = "Gentle anger, raging calm.",
		name = "Ungil's Harmony",
	},
	[193] = {
		baseType = "FourUniqueAmulet5",
		text = "The sacred sap flows slowly, but surely.",
		name = "Revered Resin",
	},
	[194] = {
		baseType = "FourUniqueAmulet6",
		text = "Forged from the blood of countless wars,\nits thirst has only begun.",
		name = "Carnage Heart",
	},
	[195] = {
		baseType = "FourUniqueAmulet7",
		text = "Natural grace is born, not earned.",
		name = "Surefooted Sigil",
	},
	[196] = {
		baseType = "FourUniqueAmulet8",
		text = "The respect of Karui warriors is hard to earn,\nbut lasts a lifetime... and beyond.",
		name = "Defiance of Destiny",
	},
	[197] = {
		baseType = "FourUniqueAmulet9",
		text = "You are slow, foolish and ignorant.\nI am not.",
		name = "Stone of Lazhwar",
	},
	[198] = {
		baseType = "FourUniqueAmulet10_",
		text = "Healing the soul requires sacrifice.",
		name = "Ligurium Talisman",
	},
	[199] = {
		baseType = "FourUniqueAmulet12",
		text = "Fanatics are the most dangerous enemy,\nfor they care not for their own survival.",
		name = "Rondel of Fragility",
	},
	[200] = {
		baseType = "FourUniqueAmulet13",
		text = "Forge your Perseverance on the Anvil of Faith.",
		name = "The Anvil",
	},
	[201] = {
		baseType = "FourUniqueAmulet14",
		text = "Let the unrepentant be dragged ever downwards by the weight of their sins.",
		name = "Yoke of Suffering",
	},
	[202] = {
		baseType = "FourUniqueAmulet15_",
		text = "Mindless rage will shake the world,\nCunning lies will bend it.\nReckless haste will break the world,\nAnd into darkness send it.",
		name = "Astramentis",
	},
	[203] = {
		baseType = "FourUniqueAmulet16",
		text = "He knew not why he was changing, only\nthat he wanted to hold his family close...",
		name = "Fixation of Yix",
	},
	[204] = {
		baseType = "FourUniqueAmulet17",
		text = "The homeguard signalled for aid against a surprise attack,\nbut it was not their dekharas that responded.\nIt was Solerai herself.",
		name = "Beacon of Azis",
	},
	[205] = {
		baseType = "FourUniqueAmulet18",
		text = "Tale-women in training drink of a painful desert fruit.\nFire, they learn, springs from agony.",
		name = "Fireflower",
	},
	[206] = {
		baseType = "FourUniqueAmulet19_",
		text = "Never blinking, always watching.",
		name = "Eye of Chayula",
	},
	[207] = {
		baseType = "FourUniqueAmulet20",
		text = "When Kabala the Serpent Queen was banished from Keth,\nthe Sekhemas took a single hostage as punishment.",
		name = "Serpent's Egg",
	},
	[208] = {
		baseType = "FourUniqueRing1",
		text = "Fear is highly infectious.",
		name = "Blackheart",
	},
	[209] = {
		baseType = "FourUniqueRing2a",
		text = "Those members of the Brotherhood who employ the venom of\nTrarthan ice snakes must take great care with the volatile substance.",
		name = "Icefang Orbit",
	},
	[210] = {
		baseType = "FourUniqueRing2b",
		text = "There is a way to survive the bite of an ice snake,\nbut few have the resolve to attempt it.",
		name = "Venopuncture",
	},
	[211] = {
		baseType = "FourUniqueRing3",
		text = "Agony brings clarity to those of pure mind.",
		name = "Prized Pain",
	},
	[212] = {
		baseType = "FourUniqueRing4",
		text = "As their eyes adjusted, they became aware of a strange\nblue light. Countless glowing worms crawled above,\nblissfully unaware of their flight from the sirens.",
		name = "Glowswarm",
	},
	[213] = {
		baseType = "FourUniqueRing5",
		text = "Where her mouth should have been there was only a whirling, black void.",
		name = "Doedre's Damning",
	},
	[214] = {
		baseType = "FourUniqueRing6",
		text = "The dawn of a new era is set into motion",
		name = "Seed of Cataclysm",
	},
	[215] = {
		baseType = "FourUniqueRing7",
		text = "Fear the fire that spreads like a plague.",
		name = "Cracklecreep",
	},
	[216] = {
		baseType = "FourUniqueRing8",
		text = "\"The Brotherhood of Silence does not set out to torture our targets.\nExcruciating pain is simply a byproduct of certain... necessary methods.\"",
		name = "Blistering Bond",
	},
	[217] = {
		baseType = "FourUniqueRing10",
		text = "I rule the north\nA legacy earned\nTime and time again\nSing Meginord's song!",
		name = "Polcirkeln",
	},
	[218] = {
		baseType = "FourUniqueRing11",
		text = "Doryani stumbled into a realm of madness\nAnd awoke its Master.",
		name = "Dream Fragments",
	},
	[219] = {
		baseType = "FourUniqueRing12",
		text = "Forged by the last remaining brother\nto return all that was once given.",
		name = "Whisper of the Brotherhood",
	},
	[220] = {
		baseType = "FourUniqueRing13",
		text = "Highgate held other secrets.",
		name = "Levinstone",
	},
	[221] = {
		baseType = "FourUniqueRing14",
		text = "It coils deeper and deeper\nIt slithers between thoughts\nIt lies beneath the valley\nIt lies in our minds",
		name = "The Burrower",
	},
	[222] = {
		baseType = "FourUniqueRing15",
		text = "Forged by three brothers\nso that they may recognize each other\nacross any distance of time or travel.",
		name = "Call of the Brotherhood",
	},
	[223] = {
		baseType = "FourUniqueRing16",
		text = "Ming slew Tranquillity\nTook Chaos for his wife\nAnd on Her immortal finger\nHe placed his Heart",
		name = "Ming's Heart",
	},
	[224] = {
		baseType = "FourUniqueRing17",
		text = "Beyond the veil of death, there burns a fire\nby whose light night is borne.",
		name = "Blackflame",
	},
	[225] = {
		baseType = "FourUniqueRing18",
		text = "Innocence rose to godhood not on inspired faith,\nbut on the vilification and hatred of another.",
		name = "Original Sin",
	},
	[226] = {
		baseType = "FourUniqueRing19",
		text = "The warriors of the Unblinking Eye moved\ntogether as one, shoulder to shoulder.",
		name = "Vigilant View",
	},
	[227] = {
		baseType = "FourUniqueRing20",
		text = "To truly appreciate life you must be there when it ends",
		name = "Death Rush",
	},
	[228] = {
		baseType = "FourUniqueRing21",
		text = "The ring I stole,\nMy finger they took,\nA shrouded mind,\nCut their curses short,\nAs I drained their spirit\nAnd stole their soul.\nA blessing is often a curse.",
		name = "Thief's Torment",
	},
	[229] = {
		baseType = "FourUniqueRing22",
		text = "Power comes to those who seek\nDeath comes to those who reach",
		name = "Evergrasping Ring",
	},
	[230] = {
		baseType = "FourUniqueRing23",
		text = "When the axe finally fell, Seryl shared his pain,\nand the last thought that flickered through his\nfading mind was her broken, shattered scream.",
		name = "Heartbound Loop",
	},
	[231] = {
		baseType = "FourUniqueRing24",
		text = "They wrap around you until your blood turns as cold as theirs.",
		name = "Snakepit",
	},
	[232] = {
		baseType = "FourUniqueRing25",
		text = "God blesses those who bless themselves.",
		name = "Gifts from Above",
	},
	[233] = {
		baseType = "FourUniqueRing28",
		text = "A pact with Prospero always comes at a price.",
		name = "Perandus Seal",
	},
	[234] = {
		baseType = "FourUniqueRing29",
		text = "Danger is the price of wealth.",
		name = "Andvarius",
	},
	[235] = {
		baseType = "FourUniqueRing30",
		text = "In a blaze of glory,\nAn anomaly defying all odds\nThe \"unkillable\" beast met the divine\nAnd Ventor met his latest trophy.",
		name = "Ventor's Gamble",
	},
	[236] = {
		baseType = "FourUniqueRing32",
		text = "Power is a matter of perspective.",
		name = "Kalandra's Touch",
	},
	[237] = {
		baseType = "FourUniqueBelt1",
		text = "Kaom's strength was rivaled only by\nthe great Meginord of the north.",
		name = "Meginord's Girdle",
	},
	[238] = {
		baseType = "FourUniqueBelt2",
		text = "Adversity is the soil in\nwhich persistence grows.",
		name = "Midnight Braid",
	},
	[239] = {
		baseType = "FourUniqueBelt3",
		text = "Below all living things,\nthere exists a flow...",
		name = "Keelhaul",
	},
	[240] = {
		baseType = "FourUniqueBelt5",
		text = "Some families have peculiar gifts...",
		name = "Birthright Buckle",
	},
	[241] = {
		baseType = "FourUniqueBelt6",
		text = "The Brinerot sail without fear of storms.",
		name = "Brynabas",
	},
	[242] = {
		baseType = "FourUniqueBelt8",
		text = "Vaal bloodpriests were among the earliest intellectuals on record.\nIt was they who found that a newly freed soul would\ndesperately cling to any other source of life.",
		name = "Soul Tether",
	},
	[243] = {
		baseType = "FourUniqueBelt9",
		text = "Tempered by the forbidden flame.",
		name = "Infernoclasp",
	},
	[244] = {
		baseType = "FourUniqueBelt10",
		text = "Bleeding just means you're still alive.",
		name = "Goregirdle",
	},
	[245] = {
		baseType = "FourUniqueBelt12",
		text = "All creatures have the potential for greatness or unequivocal failure.",
		name = "Ryslatha's Coil",
	},
	[246] = {
		baseType = "FourUniqueBelt13",
		text = "Death is your most important duty.\nFace it, or curse your bloodline for all eternity.",
		name = "Coward's Legacy",
	},
	[247] = {
		baseType = "FourUniqueBelt15",
		text = "Trifle not with the trinket mage.",
		name = "Bijouborne",
	},
	[248] = {
		baseType = "FourUniqueBelt16_",
		text = "Asinia promised vengeance beyond death,\nand she found a way to keep that promise.",
		name = "Silverpoint",
	},
	[249] = {
		baseType = "FourUniqueBelt17",
		text = "Clever artifice is not always complex.",
		name = "Waistgate",
	},
	[250] = {
		baseType = "FourUniqueBelt18_",
		text = "\"A man's soul rules from a cavern of bone, learns and\njudges through flesh-born windows. The heart is meat.\nThe head is where the Man is.\"\n- Lavianga, Advisor to Kaom",
		name = "Headhunter",
	},
	[251] = {
		baseType = "FourUniqueBelt21",
		text = "Bring mystery to life. Again and again.",
		name = "Shavronne's Satchel",
	},
	[252] = {
		baseType = "FourUniqueOneHandMace1",
		text = "The mark of the smith was widely known.",
		name = "Brynhand's Mark",
	},
	[253] = {
		baseType = "FourUniqueOneHandMace2",
		text = "Shaped metal never forgets the forge.",
		name = "Wylund's Stake",
	},
	[254] = {
		baseType = "FourUniqueOneHandMace3",
		text = "A merciful murderer swept through the streets of Sarn\nRobbing breath from the weak and worthless.",
		name = "Frostbreath",
	},
	[255] = {
		baseType = "FourUniqueOneHandMace4",
		text = "Ezomyte loyalty was not given to distant leaders.\nIt was earned by comrades in arms.",
		name = "Trenchtimbre",
	},
	[256] = {
		baseType = "FourUniqueOneHandMace5",
		text = "The Abyssals were created, not born,\nand every moment in the light was agony.",
		name = "Sculpted Suffering",
	},
	[257] = {
		baseType = "FourUniqueOneHandMace6",
		text = "Within lies a window.",
		name = "Seeing Stars",
	},
	[258] = {
		baseType = "FourUniqueOneHandMace7",
		text = "They hoped that, trapped in its prison,\nthe creature would age and perish.\nBut time would not touch the fiend.",
		name = "Nebuloch",
	},
	[259] = {
		baseType = "FourUniqueOneHandMace13",
		text = "Look the storm in the eye and you will have its respect.",
		name = "Mjölner",
	},
	[260] = {
		baseType = "FourUniqueTwoHandMace1",
		text = "There was a very clear and delicious\nreason why the Ezomytes chose to\nstop their flight and settle in Phaaryl.",
		name = "Hoghunt",
	},
	[261] = {
		baseType = "FourUniqueTwoHandMace2",
		text = "\"The crack of bone, the spray of blood.\nIs there sweeter music?\"\n- Hrimnor of the Ezomytes.",
		name = "Hrimnor's Hymn",
	},
	[262] = {
		baseType = "FourUniqueTwoHandMace3",
		text = "The art of surgery advances one mistake at a time.",
		name = "Trephina",
	},
	[263] = {
		baseType = "FourUniqueTwoHandMace4",
		text = "The mind may have no limits, but the skull sure does.",
		name = "Brain Rattler",
	},
	[264] = {
		baseType = "FourUniqueTwoHandMace5",
		text = "Secrecy and silence are powers all their own.",
		name = "The Empty Roar",
	},
	[265] = {
		baseType = "FourUniqueTwoHandMace6",
		text = "Be not deceived by the treachery of men.",
		name = "Shyaba",
	},
	[266] = {
		baseType = "FourUniqueTwoHandMace7",
		text = "The faithful may continue to serve, even after death.",
		name = "Chober Chaber",
	},
	[267] = {
		baseType = "FourUniqueTwoHandMace8",
		text = "\"The finest prosperity grows from the direst\ncarnage. Such is the nature of progress.\"\n- Doryani of the Vaal",
		name = "Quecholli",
	},
	[268] = {
		baseType = "FourUniqueTwoHandMace9",
		text = "The sea strikes the rock relentlessly.\nWhether in one day or in ten thousand years,\neventually the rock will crumble,\nand the Brine King's domain will grow.",
		name = "Tidebreaker",
	},
	[269] = {
		baseType = "FourUniqueTwoHandMace13",
		text = "The secret Order endured by publicly\npraying however the Templars demanded.\nOne day, justice would fall upon them...",
		name = "The Hammer of Faith",
	},
	[270] = {
		baseType = "FourUniqueSpear1",
		text = "The Baleful Gem's corruption lingers still...",
		name = "Splinter of Loratta",
	},
	[271] = {
		baseType = "FourUniqueSpear2",
		text = "The might of the Eternal Empire was formidable,\nbut rebels of every culture stood together as one.",
		name = "Tyranny's Grip",
	},
	[272] = {
		baseType = "FourUniqueSpear3",
		text = "The Sacred Hunt ends with mercy.",
		name = "Chainsting",
	},
	[273] = {
		baseType = "FourUniqueSpear4",
		text = "Heads fall to the sand, just as the star fell from the sky",
		name = "Skysliver",
	},
	[274] = {
		baseType = "FourUniqueSpear5",
		text = "\"You killed their Golden Sekhema. The Maraketh will think of nothing\nbut vengeance now.\" - Dimos, Advisor to General Titucius",
		name = "Daevata's Wind",
	},
	[275] = {
		baseType = "FourUniqueSpear6",
		text = "\"In the hands of Orbala, it made a god bleed.\"\n- Wranga, tale-woman of the Wahida akhara",
		name = "Tangletongue",
	},
	[276] = {
		baseType = "FourUniqueSpear7",
		text = "Born in a star of man's own make,\nfused to her hand by her last mistake.",
		name = "Saitha's Spear",
	},
	[277] = {
		baseType = "FourUniqueSpear13",
		text = "The spear was specially forged to assassinate Voll,\nbut Maligaro never got a chance to use it...",
		name = "Spire of Ire",
	},
	[278] = {
		baseType = "FourUniqueQuarterstaff1",
		text = "Touch not the thorn, for only blood and pain await.",
		name = "The Blood Thorn",
	},
	[279] = {
		baseType = "FourUniqueQuarterstaff2",
		text = "Forged to rule the waves and tide\nDestined to serve the monkey's paw\nStrong as a tower of iron\nDeft as the needle doubt",
		name = "Pillar of the Caged God",
	},
	[280] = {
		baseType = "FourUniqueQuarterstaff3",
		text = "The night Draven attacked,\nErian was asleep at his post.",
		name = "The Sentry",
	},
	[281] = {
		baseType = "FourUniqueQuarterstaff5",
		text = "In our tales, and in our hearts, the rivers still flow.",
		name = "Matsya",
	},
	[282] = {
		baseType = "FourUniqueQuarterstaff6",
		text = "The first witch hunter knew one critical tactic:\nnever let your enemy have a clear moment.",
		name = "Nazir's Judgement",
	},
	[283] = {
		baseType = "FourUniqueWand1",
		text = "With a flick of the finger, their fates are written,\nthe pages torn to a million pieces.",
		name = "The Wicked Quill",
	},
	[284] = {
		baseType = "FourUniqueWand2",
		text = "One way or another, it will find what it seeks.",
		name = "Sanguine Diviner",
	},
	[285] = {
		baseType = "FourUniqueWand3",
		text = "From the smallest seeds\nTo the tallest redwoods,\nLife endures in Wraeclast.",
		name = "Lifesprig",
	},
	[286] = {
		baseType = "FourUniqueWand5",
		text = "He alone was welcome in the sacred spaces of the Titans.",
		name = "Enezun's Charge",
	},
	[287] = {
		baseType = "FourUniqueWand7",
		text = "Lost in the Black Fen, Erian hoped that dawn would save him. He had no idea how far away the light truly was.",
		name = "Cursecarver",
	},
	[288] = {
		baseType = "FourUniqueStaff1",
		text = "The candlemass tradition was born in a time of darkness and fear.",
		name = "Dusk Vigil",
	},
	[289] = {
		baseType = "FourUniqueStaff2",
		text = "Shed by the winged beast of night,\nA scaly frost-encrusted thorn.\nAll who feel its wintry light\nShiver in pain at the frozen dawn.",
		name = "Taryn's Shiver",
	},
	[290] = {
		baseType = "FourUniqueStaff3",
		text = "An ancient Azmeri staff, overgrown by roots...",
		name = "Earthbound",
	},
	[291] = {
		baseType = "FourUniqueStaff5",
		text = "Burn to cinders, scar and maim,\nRule a world, bathed in flame.",
		name = "The Searing Touch",
	},
	[292] = {
		baseType = "FourUniqueStaff6",
		text = "That which was broken may yet break.",
		name = "Sire of Shards",
	},
	[293] = {
		baseType = "FourUniqueBow1",
		text = "\"I loosed a volley of arrows into the heart of the man\nwho slew my beloved. There was no satisfaction, no\nhealing, no revenge. There was only... emptiness.\"",
		name = "Widowhail",
	},
	[294] = {
		baseType = "FourUniqueBow2",
		text = "\"The rain of a thousand quills that whittle\npresent into past, life into death.\"\n- Rigwald of the Ezomytes",
		name = "Quill Rain",
	},
	[295] = {
		baseType = "FourUniqueBow4",
		text = "The forests of the Vastiri held many secrets\nmystical and dark. Men learned not to wander,\nlest they return with a strange new purpose.",
		name = "Splinterheart",
	},
	[296] = {
		baseType = "FourUniqueBow5",
		text = "\"Toasted or frozen\nOr twitching in the light\nI'm not fussy\nAnd neither is Death.\"\n- Koralus Doomfletch",
		name = "Doomfletch",
	},
	[297] = {
		baseType = "FourUniqueBow6",
		text = "The mournful music of the strings,\nThe creaking arch, the arrow sings.\nA choking cry, a rattled breath,\nThe Reaper's Song, the Harp of Death.",
		name = "Death's Harp",
	},
	[298] = {
		baseType = "FourUniqueBow7",
		text = "The eldritch storm descended upon us, and bruised lightning\nrained down. Metal withered and flesh melted before its\narcane power. There was no escape, no shelter. Only despair.",
		name = "Voltaxic Rift",
	},
	[299] = {
		baseType = "FourUniqueBow8",
		text = "A hundred blind heads, each seeking the taste of prey on the air.",
		name = "Slivertongue",
	},
	[300] = {
		baseType = "FourUniqueCrossbow1",
		text = "Sibilant promises surrounded them in the night.\nAll the travelers had to give him was their devotion...",
		name = "Mist Whisper",
	},
	[301] = {
		baseType = "FourUniqueCrossbow2",
		text = "\"His approach to the gate was met with sounding trumpets\nand an unfurling of banners. He never saw it coming.\"\n- anonymous Brotherhood of Silence report",
		name = "Rampart Raptor",
	},
	[302] = {
		baseType = "FourUniqueSceptre1",
		text = "Rare is the Necromancer who leads\nhis undead armies from the front.",
		name = "The Dark Defiler",
	},
	[303] = {
		baseType = "FourUniqueSceptre4",
		text = "Tale-women may not fight directly,\nfor they have a much higher purpose.",
		name = "Font of Power",
	},
	[304] = {
		baseType = "FourUniqueSceptre6",
		text = "The stories we tell serve to unite us.",
		name = "Guiding Palm",
	},
	[305] = {
		baseType = "FourUniqueCharm1",
		text = "\"Even in the face of the Winter of the World,\nlife found a way. The Spirit always provides.\"",
		name = "Nascent Hope",
	},
	[306] = {
		baseType = "FourUniqueCharm2",
		text = "Wraeclast has known too few true heroes.\nIt remembers those that stood in defiance.",
		name = "Sanguis Heroum",
	},
	[307] = {
		baseType = "FourUniqueCharm3",
		text = "Devotees of the Goddess of Lust\nneeded never fear her sting.",
		name = "Arakaali's Gift",
	},
	[308] = {
		baseType = "FourUniqueCharm4",
		text = "They found a crying child tied to a frozen pyre.\nShe was clad in ice, but the village was ash.",
		name = "Beira's Anguish",
	},
	[309] = {
		baseType = "FourUniqueCharm5",
		text = "The most beloved member of every Brinerot crew\nis the one that refuses to do any actual work.",
		name = "The Black Cat",
	},
	[310] = {
		baseType = "FourUniqueCharm6",
		text = "\"It may be centuries hence, but I still hold utmost faith.\nThe Savior will rise, and mankind will be free.\"",
		name = "For Utopia",
	},
	[311] = {
		baseType = "FourUniqueCharm7",
		text = "\"When the headsman's blade swings,\nyour last moments stretch to eternity.\"\n- Vorm, the Twice-Pardoned",
		name = "The Fall of the Axe",
	},
	[312] = {
		baseType = "FourUniqueCharm8",
		text = "Kaom was not known for his restraint.",
		name = "Ngamahu's Chosen",
	},
	[313] = {
		baseType = "FourUniqueCharm9",
		text = "\"To scrape the sky,\nto touch the clouds themselves,\nis to know true freedom.\"\n- Mutewind saying",
		name = "Breath of the Mountains",
	},
	[314] = {
		baseType = "FourUniqueCharm10",
		text = "The sea swells, the sky thunders; two ships tilt at odds.\nFlashes of light show only swinging axes... and a grin.",
		name = "Valako's Roar",
	},
	[315] = {
		baseType = "FourUniqueCharm11",
		text = "Among the Templars, a secret few ate the sins of others.\nThey bore this burden to empower their hidden Order.",
		name = "Forsaken Bangle",
	},
	[316] = {
		baseType = "FourUniquePinnacle1",
		text = "The Unblinking Eye did not cower and wail.\nThey stood against the end.",
		name = "Morior Invictus",
	},
	[317] = {
		baseType = "FourUniquePinnacle2",
		text = "One warrior alone survived to face the Arbiter.",
		name = "Solus Ipse",
	},
	[318] = {
		baseType = "FourUniquePinnacle3",
		text = "The greatest warrior of his era fought with honour.",
		name = "Sine Aequo",
	},
	[319] = {
		baseType = "FourUniquePinnacle4",
		text = "His enemy was for endurance forged. His own waned.",
		name = "Ab Aeterno",
	},
	[320] = {
		baseType = "FourUniquePinnacle5",
		text = "Fire destroys, but fire also purifies.\nLife always springs anew.",
		name = "Sacred Flame",
	},
	[321] = {
		baseType = "FourUniqueSanctum1",
		text = "The final element the tale-women\nmastered was Time itself.",
		name = "Temporalis",
	},
	[322] = {
		baseType = "FourUniqueSanctum2",
		text = "A fell wind brings death.",
		name = "Sandstorm Visage",
	},
	[323] = {
		baseType = "FourUniqueSanctum3",
		text = "\"We survived the endless winter.\nWe endure the long summer.\nOne day, spring will return the rains.\"",
		name = "Blessed Bonds",
	},
	[324] = {
		baseType = "FourUniqueSanctum4a",
		text = "Though the summer of centuries burns the\nVastiri to dust, we remain, unchanged.",
		name = "Sekhema's Resolve",
	},
	[325] = {
		baseType = "FourUniqueSanctum4b",
		text = "Though the Winter of the World shrouded the\nVastiri in ice, we remained, unchanged.",
		name = "Sekhema's Resolve",
	},
	[326] = {
		baseType = "FourUniqueSanctum4c",
		text = "Though the rains refuse to return to a dry\nVastiri, we shall remain, unchanged.",
		name = "Sekhema's Resolve",
	},
	[327] = {
		baseType = "FourUniqueUltimatum1",
		text = "Man retains sanity and strives toward civilisation\nonly under the blessed veil of ignorance.",
		name = "Glimpse of Chaos",
	},
	[328] = {
		baseType = "FourUniqueUltimatum2",
		text = "The most horrifying ideas often begin with a simple innovation.",
		name = "Zerphi's Genesis",
	},
	[329] = {
		baseType = "FourUniqueUltimatum3",
		text = "The Banished Architect sought to employ the darkest secrets of the Vaal.",
		name = "Mahuxotl's Machination",
	},
	[330] = {
		baseType = "FourUniqueUltimatum4",
		text = "The first Karui born on the fringes of the Vaal empire developed a blood fever born of corruption.",
		name = "Hateforge",
	},
	[331] = {
		baseType = "FourUniqueExpedition1",
		text = "The priests found the Great Shield the night it fell to Middengard,\nbut it was the smiths who delved into the secrets it held.",
		name = "Svalinn",
	},
	[332] = {
		baseType = "FourUniqueExpedition2",
		text = "The priests of the Kalguur keep faith through numbers\nand calculation, not unprovable promises.",
		name = "Keeper of the Arc",
	},
	[333] = {
		baseType = "FourUniqueExpedition3_",
		text = "Olroth the Gallant,\ntireless and true,\nhe fights for me,\nhe fights for you!",
		name = "Olroth's Resolve",
	},
	[334] = {
		baseType = "FourUniqueExpedition4",
		text = "\"True heroes grow stronger in the face of adversity.\"\n- Fourth Tenet of the Knights of the Sun",
		name = "Olrovasara",
	},
	[335] = {
		baseType = "FourUniqueDelirium1",
		text = "A moment of calm before the battle can end the war.",
		name = "Assailum",
	},
	[336] = {
		baseType = "FourUniqueDelirium2",
		text = "The Trickster God turned the very Day and Night against each other.\nWhat hope have you?",
		name = "Perfidy",
	},
	[337] = {
		baseType = "FourUniqueDelirium3",
		text = "What is life, but a dreamlike spiral of panic?",
		name = "Melting Maelstrom",
	},
	[338] = {
		baseType = "FourUniqueDelirium4",
		text = "The edges bend, the world flexes, the infinite spills into view.",
		name = "Collapsing Horizon",
	},
	[339] = {
		baseType = "FourUniqueDelirium5",
		text = "There is no light at the end of this inner strife,\nbut the shadows eventually become home.",
		name = "Strugglescream",
	},
	[340] = {
		baseType = "FourUniqueRitual1",
		text = "Nothingness is loathe to relinquish its grip.\nEvery moment is a struggle to exist.",
		name = "The Burden of Shadows",
	},
	[341] = {
		baseType = "FourUniqueRitual2",
		text = "They crawl and chitter and swarm\nin the shadow of his presence.",
		name = "Beetlebite",
	},
	[342] = {
		baseType = "FourUniqueRitual3",
		text = "Experiments with geomancy taught\nthe Maji more than they ever expected.",
		name = "Ingenuity",
	},
	[343] = {
		baseType = "FourUniqueRitual4",
		text = "In an endless war against darkness,\none must be ever vigilant.",
		name = "Pragmatism",
	},
	[344] = {
		baseType = "FourUniqueBreach1_",
		text = "We happily give our limbs.\nA net woven to keep safe the bones of the Lords.",
		name = "Skin of the Loyal",
	},
	[345] = {
		baseType = "FourUniqueBreach2",
		text = "She thinks and we act.\nShe acts and we think.\nFragments of the whole that washes clean the skies.",
		name = "Hand of Wisdom and Action",
	},
	[346] = {
		baseType = "FourUniqueBreach3",
		text = "The limit of our knowledge is a barrier\nthat protects us from ourselves.",
		name = "Beyond Reach",
	},
	[347] = {
		baseType = "FourUniqueBreach4a",
		text = "We are his blood.\nThrough us he carries his burning message.",
		name = "Xoph's Blood",
	},
	[348] = {
		baseType = "FourUniqueBreach4b",
		text = "But the fool did not bow.\nThe fool stood and questioned.\nAnd the fool was unwritten.",
		name = "Choir of the Storm",
	},
	[349] = {
		baseType = "FourUniqueBreach4c",
		text = "A single moment sets in motion an eternal fall,\nbeneath which all are buried.",
		name = "The Pandemonius",
	},
	[350] = {
		baseType = "FourUniqueSpirit1",
		text = "To become a warrior and a hunter, each young\nAzmeri must prove themselves before the Spirit.",
		name = "Rite of Passage",
	},
	[351] = {
		baseType = "FourUniqueCorruption1",
		text = "\"Ghorr knows only hunger, only ravenous feasting.\nIt will consume all that lives, and more!\"\n- Rantings of a Templar prisoner, page fourteen",
		name = "The Gnashing Sash",
	},
	[352] = {
		baseType = "FourUniqueCorruption2",
		text = "\"All Beidat desires is a foothold, a grip on your flesh,\non the world... he will offer you anything to get it...\"\n- Rantings of a Templar prisoner, page thirty",
		name = "Bursting Decay",
	},
	[353] = {
		baseType = "FourUniqueCorruption3",
		text = "\"The mind at the center of the swarm... K'Tash does\nthe thinking... but it has only one thought... hate.\"\n- Rantings of a Templar prisoner, page ninety-four",
		name = "Death Articulated",
	},
	[354] = {
		baseType = "FourUniqueJewel1",
		text = "A wellspring of vitality bubbling from within.",
		name = "Grand Spectrum",
	},
	[355] = {
		baseType = "FourUniqueJewel2",
		text = "An indomitable force of control.",
		name = "Grand Spectrum",
	},
	[356] = {
		baseType = "FourUniqueJewel3",
		text = "Skin like steel tempered by bright flames.",
		name = "Grand Spectrum",
	},
	[357] = {
		baseType = "FourUniqueJewel4",
		text = "If you're going to act like you're better\nthan everyone else, make sure you are.",
		name = "Megalomaniac",
	},
	[358] = {
		baseType = "FourUniqueJewel5",
		text = "They believed themselves courageous and selfless,\nbut that bravery became the doom at their door.",
		name = "Heroic Tragedy",
	},
	[359] = {
		baseType = "FourUniqueJewel6",
		text = "They clawed their way up from the agonising depths of nonexistence,\nbreathing deep with joy the exquisite light of meaning.",
		name = "From Nothing",
	},
	[360] = {
		baseType = "FourUniqueJewel7",
		text = "Our world was dying, but we chose to survive.\nWe broke free from the chains within.",
		name = "Controlled Metamorphosis",
	},
	[361] = {
		baseType = "FourUniqueJewel8",
		text = "Entropy can be reversed.",
		name = "Prism of Belief",
	},
	[362] = {
		baseType = "FourUniqueJewel9",
		text = "At their height, the Vaal glittered under the sun.\nA decade, a century, an aeon of prosperity...\nnow nothing more than a passing wonder.",
		name = "The Adorned",
	},
	[363] = {
		baseType = "FourUniqueJewel10",
		text = "After the fires, in the depths of the Winter of the World, all life in the Vastiri banded together. Whether serpent, hyena, human, or golem, hated enemies clasped hand to claw, built refuge, and fought side by side against the Abyssals. Thus, the Third Pact was born.",
		name = "Against the Darkness",
	},
}
