-- This file is automatically generated, do not edit!
-- Game data (c) Grinding Gear Games

-- Item modifier data generated by mods.lua

-- spell-checker: disable
return {
	["IncursionArm1"] = {
		"(8-12)% increased Block chance",
		["affix"] = "",
		["group"] = "IncreasedBlockChance",
		["level"] = 0,
		["modTags"] = {
			"block",
		},
		["statOrder"] = {
			1133,
		},
		["tradeHashes"] = {
			[4147897060] = {
				"(8-12)% increased Block chance",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionArm2"] = {
		"(6-10)% increased Attack Speed",
		["affix"] = "",
		["group"] = "IncreasedAttackSpeed",
		["level"] = 0,
		["modTags"] = {
			"attack",
			"speed",
		},
		["statOrder"] = {
			985,
		},
		["tradeHashes"] = {
			[681332047] = {
				"(6-10)% increased Attack Speed",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionArm3"] = {
		"(6-10)% increased Cast Speed",
		["affix"] = "",
		["group"] = "IncreasedCastSpeed",
		["level"] = 0,
		["modTags"] = {
			"caster_speed",
			"caster",
			"speed",
		},
		["statOrder"] = {
			987,
		},
		["tradeHashes"] = {
			[2891184298] = {
				"(6-10)% increased Cast Speed",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionArm4"] = {
		"(12-16)% increased Curse Magnitudes",
		["affix"] = "",
		["group"] = "CurseEffectiveness",
		["level"] = 0,
		["modTags"] = {
			"caster",
			"curse",
		},
		["statOrder"] = {
			2376,
		},
		["tradeHashes"] = {
			[2353576063] = {
				"(12-16)% increased Curse Magnitudes",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionArm5"] = {
		"(6-10)% increased Deflection Rating",
		["affix"] = "",
		["group"] = "GlobalDeflectionRating",
		["level"] = 0,
		["modTags"] = {
			"defences",
			"evasion",
		},
		["statOrder"] = {
			6119,
		},
		["tradeHashes"] = {
			[3040571529] = {
				"(6-10)% increased Deflection Rating",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionArm6"] = {
		"(15-25)% increased Presence Area of Effect",
		["affix"] = "",
		["group"] = "PresenceRadius",
		["level"] = 0,
		["modTags"] = {
			"aura",
		},
		["statOrder"] = {
			1069,
		},
		["tradeHashes"] = {
			[101878827] = {
				"(15-25)% increased Presence Area of Effect",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg1"] = {
		"(20-30)% increased Evasion Rating",
		["affix"] = "",
		["group"] = "GlobalEvasionRatingPercent",
		["level"] = 0,
		["modTags"] = {
			"defences",
			"evasion",
		},
		["statOrder"] = {
			884,
		},
		["tradeHashes"] = {
			[2106365538] = {
				"(20-30)% increased Evasion Rating",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg2"] = {
		"(6-10)% increased Movement Speed while Sprinting",
		["affix"] = "",
		["group"] = "MovementVelocityWhileSprinting",
		["level"] = 0,
		["modTags"] = {
			"speed",
		},
		["statOrder"] = {
			10069,
		},
		["tradeHashes"] = {
			[3107707789] = {
				"(6-10)% increased Movement Speed while Sprinting",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg3"] = {
		"(15-25)% increased Stun Threshold",
		["affix"] = "",
		["group"] = "IncreasedStunThreshold",
		["level"] = 0,
		["modTags"] = {
		},
		["statOrder"] = {
			2983,
		},
		["tradeHashes"] = {
			[680068163] = {
				"(15-25)% increased Stun Threshold",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg4"] = {
		"(5-10)% reduced Movement Speed Penalty from using Skills while moving",
		["affix"] = "",
		["group"] = "MovementVelocityPenaltyWhilePerformingAction",
		["level"] = 0,
		["modTags"] = {
			"speed",
		},
		["statOrder"] = {
			9154,
		},
		["tradeHashes"] = {
			[2590797182] = {
				"(5-10)% reduced Movement Speed Penalty from using Skills while moving",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg5"] = {
		"(20-30)% increased Mana Regeneration Rate while moving",
		["affix"] = "",
		["group"] = "ManaRegenerationRateWhileMoving",
		["level"] = 0,
		["modTags"] = {
			"resource",
			"mana",
		},
		["statOrder"] = {
			8021,
		},
		["tradeHashes"] = {
			[1327522346] = {
				"(20-30)% increased Mana Regeneration Rate while moving",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
	["IncursionLeg6"] = {
		"(6-10)% of Damage taken Recouped as Life",
		["affix"] = "",
		["group"] = "DamageTakenGainedAsLife",
		["level"] = 0,
		["modTags"] = {
			"resource",
			"life",
		},
		["statOrder"] = {
			1037,
		},
		["tradeHashes"] = {
			[1444556985] = {
				"(6-10)% of Damage taken Recouped as Life",
			},
		},
		["weightKey"] = {
		},
		["weightVal"] = {
		},
	},
}
