-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Spectre Data
-- Monster data (c) Grinding Gear Games
--
local minions, mod, flag = ...

-- Beyond
minions["Metadata/Monsters/LeagueHellscape/PaleFaction/HellscapePaleElite1_"] = {
	name = "Pale Angel",
	monsterTags = { "beyond_demon", "demon", "medium_movement", "not_dex", "not_str", "red_blood", "Unarmed_onhit_audio", },
	life = 2.12,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.12,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 2.35,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	weaponType1 = "None",
	skillList = {
		"TBHellscapePaleLightningBoltSpammableLeft",
		"TBHellscapePaleLightningBoltSpammableRight",
		"GSHellscapePaleEliteBoltImpact",
		"GSHellscapePaleEliteOmegaBeam",
		"TeleportHellscapePaleElite",
	},
	modList = {
	},
}
minions["Metadata/Monsters/LeagueHellscape/PaleFaction/HellscapePaleElite2__"] = {
	name = "Pale Seraphim",
	monsterTags = { "beyond_demon", "demon", "fast_movement", "MonsterStab_onhit_audio", "not_int", "pale_faction", "red_blood", },
	life = 2.25,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.25,
	evasion = 0.25,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1.97,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 18,
	accuracy = 1,
	weaponType1 = "None",
	skillList = {
		"DTTHellscapeStabbySkyStab",
		"DTTHellscapeStabWeb",
		"GAHellscapeStabWeb",
		"GAHellscapePaleEliteSkyStab",
		"TCHellscapePaleElite2Charge",
		"GSHellscapePaleElite2Charge",
		"MeleeAtAnimationSpeedLightning",
		"MeleeAtAnimationSpeedLightningCombo35",
	},
	modList = {
		-- HellscapeYellowLightningOverride [shock_art_variation = 10]
		-- HellscapeYellowLightningOverride [damage_hit_effect_index = 103]
	},
}

-- Boar
minions["Metadata/Monsters/GoreCharger/GoreCharger"] = {
	name = "Diretusk Boar",
	monsterTags = { "beast", "mammal_beast", "medium_movement", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", },
	life = 1.7,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.3,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.7,
	damageSpread = 0.2,
	attackTime = 1.065,
	attackRange = 13,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GoreChargerCharge",
	},
	modList = {
		mod("BleedChance", "BASE", 25, 1, 0), -- MonsterBleedOnHitChance [bleed_on_hit_with_attacks_% = 25]
	},
}

-- Dinosaur
minions["Metadata/Monsters/BoneCultists/BoneCultists_Beast/BoneCultistBeast"] = {
	name = "Drudge Osseodon",
	monsterTags = { "beast", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", "reptile_beast", "slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.75,
	damageSpread = 0.2,
	attackTime = 1.665,
	attackRange = 19,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"CultistBeastSunder",
	},
	modList = {
	},
}

-- Goliath
minions["Metadata/Monsters/TwoheadedTitan/TwoHeadedTitan"] = {
	name = "Goliath",
	monsterTags = { "allows_inc_aoe", "humanoid", "melee", "MonsterBlunt_onhit_audio", "physical_affinity", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 20,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GATwoHeadedTitanSlam",
		"GATwoHeadedTitanStomp",
	},
	modList = {
	},
}

-- Scarab
minions["Metadata/Monsters/EtchedBeetles/MediumEtchedBeetleArmouredDull"] = {
	name = "Tarnished Scarab",
	monsterTags = { "2HSharpMetal_onhit_audio", "allows_inc_aoe", "beast", "fast_movement", "insect", "lightning_affinity", "melee", "not_dex", "not_int", },
	life = 1.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = -30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GAMediumBeetleChargedSunder",
		"GAMediumBeetleSunder",
	},
	modList = {
	},
}

-- Sentinel
minions["Metadata/Monsters/VaalConstructs/Sentinel/VaalConstructSentinel"] = {
	name = "Stone Sentinel",
	monsterTags = { "2HBluntWood_onhit_audio", "allows_inc_aoe", "cannot_be_monolith", "construct", "melee", "not_dex", "not_int", "physical_affinity", "stone_construct", "vaal", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 13,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GAVaalConstructSentinelGroundSlam",
		"GAVaalConstructSentinelFootSlam",
		"GAVaalConstructSentinelImpact",
	},
	modList = {
	},
}

-- Shade -- not working, error CalcActiveSkill.lua 909 grantedEffect (nil)
--spectre Metadata/Monsters/VaalMonsters/Machinarium/Wraith/ProwlingShade

-- Quadrilla
minions["Metadata/Monsters/Quadrilla/Quadrilla"] = {
	name = "Quadrilla",
	monsterTags = { "allows_inc_aoe", "beast", "fast_movement", "mammal_beast", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.75,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 21,
	accuracy = 1,
	skillList = {
		"GAQuadrillaSunder",
		"EAAQuadrillaThrow",
		"MeleeAtAnimationSpeed",
		"GPAQuadrillaRock",
		"SSMQuadrillaRock",
		"QuadrillaShieldCharge",
		"TCQuadrillaCharge",
		"EASQuadrillaTaunt",
	},
	modList = {
	},
}

-- Vaal Humanoid
minions["Metadata/Monsters/VaalMonsters/Living/VaalGuardMortarLiving"] = {
	name = "Vaal Guard",
	monsterTags = { "allows_additional_projectiles", "allows_inc_aoe", "fire_affinity", "human", "humanoid", "not_int", "not_str", "ranged", "red_blood", "Unarmed_onhit_audio", "very_slow_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"MMSVaalGuardGrenade",
		"MMSVaalGuardOilTrap",
		"MMSVaalGuardGrenadeDeath",
		"MMSVaalGuardOilTrapDeath",
	},
	modList = {
		-- SpectrePlayDeathAction [is_spectre_with_death_action = 1]
	},
}
minions["Metadata/Monsters/VaalMonsters/Living/BloodPriests/VaalBloodPriestMale"] = {
	name = "Blood Priest",
	monsterTags = { "1HSword_onhit_audio", "allows_additional_projectiles", "allows_inc_aoe", "caster", "cultist", "fast_movement", "human", "humanoid", "not_str", "physical_affinity", "ranged", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.08,
	evasion = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "Dagger",
	skillList = {
		"MeleeAtAnimationSpeed",
		"VaalBloodPriestExsanguinate",
		"VaalBloodPriestDetonateDead",
		"MPSVaalBloodPriestProj",
		"EGBloodPriestSacrifice",
		"EASBloodPriestSummonElemental",
		"CGEBloodPriestBoilingBlood",
	},
	modList = {
	},
}
minions["Metadata/Monsters/VaalMonsters/Living/BloodPriests/VaalBloodPriestFemale"] = {
	name = "Blood Priestess",
	monsterTags = { "1HSword_onhit_audio", "allows_additional_projectiles", "allows_inc_aoe", "caster", "cultist", "fast_movement", "human", "humanoid", "not_str", "physical_affinity", "ranged", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.08,
	evasion = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "Dagger",
	skillList = {
		"MeleeAtAnimationSpeed",
		"VaalBloodPriestSoulrend",
		"EGBloodPriestVolatileDead",
		"MPSVaalBloodPriestProj",
		"EGBloodPriestSacrifice",
		"EASBloodPriestSummonElemental",
	},
	modList = {
	},
}
