-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Spectre Data
-- Monster data (c) Grinding Gear Games
--
local minions, mod, flag = ...

-- Goliath
minions["Metadata/Monsters/TwoheadedTitan/TwoHeadedTitan"] = {
	name = "Goliath",
	monsterTags = { "allows_inc_aoe", "humanoid", "melee", "MonsterBlunt_onhit_audio", "physical_affinity", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.88,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 20,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GATwoHeadedTitanSlam",
		"GATwoHeadedTitanStomp",
	},
	modList = {
	},
}

-- Quadrilla
minions["Metadata/Monsters/Quadrilla/Quadrilla"] = {
	name = "Quadrilla",
	monsterTags = { "allows_inc_aoe", "beast", "fast_movement", "mammal_beast", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.75,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 21,
	accuracy = 1,
	skillList = {
		"GAQuadrillaSunder",
		"EAAQuadrillaThrow",
		"MeleeAtAnimationSpeed",
		"GPAQuadrillaRock",
		"SSMQuadrillaRock",
		"QuadrillaShieldCharge",
		"TCQuadrillaCharge",
		"EASQuadrillaTaunt",
	},
	modList = {
	},
}

-- Sentinel
minions["Metadata/Monsters/VaalConstructs/Sentinel/VaalConstructSentinel"] = {
	name = "Stone Sentinel",
	monsterTags = { "2HBluntWood_onhit_audio", "allows_inc_aoe", "cannot_be_monolith", "construct", "melee", "not_dex", "not_int", "physical_affinity", "stone_construct", "vaal", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 13,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeed",
		"GAVaalConstructSentinelGroundSlam",
		"GAVaalConstructSentinelFootSlam",
		"GAVaalConstructSentinelImpact",
	},
	modList = {
	},
}

-- Shade
minions["Metadata/Monsters/VaalMonsters/Machinarium/Wraith/ProwlingShade"] = {
	name = "Prowling Shade",
	monsterTags = { "allows_inc_aoe", "caster", "Claw_onhit_audio", "cold_affinity", "fast_movement", "ghost", "ghost_blood", "melee", "not_str", "undead", },
	life = 2.25,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.132,
	evasion = 0.33,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.25,
	damageSpread = 0.2,
	attackTime = 1.32,
	attackRange = 16,
	accuracy = 1,
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"GSProwlingShadeIceBeam",
		"DTTProwlingShadeDash",
		"MeleeAtAnimationSpeedComboTEMP2",
	},
	modList = {
	},
}
