-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Spectre Data
-- Monster data (c) Grinding Gear Games
--
local minions, mod, flag = ...

-- Beyond
minions["Metadata/Monsters/LeagueHellscape/PaleFaction/HellscapePaleElite1_"] = {
	name = "Pale Angel",
	monsterTags = { "beyond_demon", "demon", "medium_movement", "not_dex", "not_str", "red_blood", "Unarmed_onhit_audio", },
	life = 2.12,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.12,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 2.35,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	weaponType1 = "None",
	spectreReservation = 120,
	companionReservation = 45.9,
	monsterCategory = "Demon",
	skillList = {
		"TBHellscapePaleLightningBoltSpammableLeft",
		"TBHellscapePaleLightningBoltSpammableRight",
		"GSHellscapePaleEliteBoltImpact",
		"GSHellscapePaleEliteOmegaBeam",
		"TeleportHellscapePaleElite",
	},
	modList = {
	},
}
minions["Metadata/Monsters/LeagueHellscape/PaleFaction/HellscapePaleElite2__"] = {
	name = "Pale Seraphim",
	monsterTags = { "beyond_demon", "demon", "fast_movement", "MonsterStab_onhit_audio", "not_int", "pale_faction", "red_blood", },
	life = 2.25,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.25,
	evasion = 0.25,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1.97,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 18,
	accuracy = 1,
	weaponType1 = "None",
	spectreReservation = 110,
	companionReservation = 45,
	monsterCategory = "Demon",
	skillList = {
		"DTTHellscapeStabbySkyStab",
		"DTTHellscapeStabWeb",
		"GAHellscapeStabWeb",
		"GAHellscapePaleEliteSkyStab",
		"TCHellscapePaleElite2Charge",
		"GSHellscapePaleElite2Charge",
		"MeleeAtAnimationSpeedLightning",
		"MeleeAtAnimationSpeedLightningCombo35",
	},
	modList = {
		-- HellscapeYellowLightningOverride [shock_art_variation = 10]
		-- HellscapeYellowLightningOverride [damage_hit_effect_index = 103]
	},
}

-- Boar
minions["Metadata/Monsters/GoreCharger/GoreCharger"] = {
	name = "Diretusk Boar",
	monsterTags = { "beast", "mammal_beast", "medium_movement", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", },
	life = 1.7,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.3,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.7,
	damageSpread = 0.2,
	attackTime = 1.065,
	attackRange = 13,
	accuracy = 1,
	spectreReservation = 90,
	companionReservation = 39,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeed",
		"GoreChargerCharge",
	},
	modList = {
		mod("BleedChance", "BASE", 25, 1, 0), -- MonsterBleedOnHitChance [bleed_on_hit_with_attacks_% = 25]
	},
}

-- Crab
minions["Metadata/Monsters/QuillCrab/QuillCrabBigPoison_"] = {
	name = "Venomous Crab Matriarch",
	monsterTags = { "allows_additional_projectiles", "beast", "insect", "monster_applies_poison", "MonsterStab_onhit_audio", "not_dex", "not_int", "physical_affinity", "ranged", "red_blood", "slow_movement", },
	life = 0.85,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.25,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.85,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 50,
	accuracy = 1,
	spectreReservation = 40,
	companionReservation = 27.6,
	monsterCategory = "Beast",
	skillList = {
		"QuillCrabSpikeBurstEmptyAction",
		"QuillCrabSpikeBurstPoison",
		"QuillCrabSpikeShrapnelAudioPoison",
		"QuillCrabSpikeShrapnelPoison",
	},
	modList = {
	},
}
minions["Metadata/Monsters/QuillCrab/QuillCrabTropical"] = {
	name = "Quill Crab",
	monsterTags = { "beast", "crustacean_beast", "MonsterStab_onhit_audio", "not_dex", "not_int", "red_blood", "slow_movement", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.25,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.7,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	spectreReservation = 40,
	companionReservation = 25.2,
	monsterCategory = "Beast",
	skillList = {
		"QuillCrabSpikeBurstEmptyAction",
		"QuillCrabSpikeBurstTropical",
		"QuillCrabSpikeShrapnelTropical",
		"CGEQuillCrabTropicalChill",
		"GSQuillCrabColdImpact",
	},
	modList = {
	},
}
minions["Metadata/Monsters/QuillCrab/QuillCrab"] = {
	name = "Porcupine Crab",
	monsterTags = { "allows_additional_projectiles", "beast", "fire_affinity", "insect", "MonsterStab_onhit_audio", "not_dex", "not_int", "physical_affinity", "ranged", "red_blood", "slow_movement", },
	life = 0.7,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.25,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.7,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	spectreReservation = 40,
	companionReservation = 25.2,
	monsterCategory = "Beast",
	skillList = {
		"QuillCrabSpikeBurstEmptyAction",
		"QuillCrabSpikeBurst",
		"QuillCrabSpikeShrapnelAudio",
		"QuillCrabSpikeShrapnel",
	},
	modList = {
	},
}
minions["Metadata/Monsters/ShellMonster/ShellMonster"] = {
	name = "Brimstone Crab",
	monsterTags = { "allows_additional_projectiles", "allows_inc_aoe", "beast", "crustacean_beast", "fire", "fire_affinity", "melee", "MonsterStab_onhit_audio", "not_dex", "not_int", "ranged", "slow_movement", },
	life = 1.15,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.15,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 9,
	accuracy = 1,
	spectreReservation = 60,
	companionReservation = 32.1,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"ShellMonsterFirehose",
		"ShellMonsterDeathMortar",
		"EDSShellMonsterFlamethrower",
		"ShellMonsterSprayMortar",
	},
	modList = {
		-- SpectrePlayDeathAction [is_spectre_with_death_action = 1]
	},
}
minions["Metadata/Monsters/ShellMonster/ShellMonsterPoison"] = {
	name = "Caustic Crab",
	monsterTags = { "allows_additional_projectiles", "beast", "crustacean_beast", "MonsterStab_onhit_audio", "not_dex", "not_int", "physical_affinity", "ranged", "slow_movement", },
	life = 1.15,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = -30,
	chaosResist = 0,
	damage = 1.15,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 9,
	accuracy = 1,
	spectreReservation = 60,
	companionReservation = 32.1,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"ShellMonsterDeathMortarPoison",
		"EDSShellMonsterPoisonSpray",
		"ShellMonsterSprayMortarPoison",
	},
	modList = {
		-- SpectrePlayDeathAction [is_spectre_with_death_action = 1]
	},
}

-- Demon
minions["Metadata/Monsters/Sanctified/Monstrosity/SanctifiedMonstrosity"] = {
	name = "Fettered Monstrosity",
	monsterTags = { "demon", "medium_movement", "MonsterBlunt_onhit_audio", "mud_blood", },
	life = 3.5,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.28,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 28,
	accuracy = 1,
	spectreReservation = 180,
	companionReservation = 56.1,
	monsterCategory = "Demon",
	skillList = {
		"MeleeAtAnimationSpeed",
		"MPWCleansedMonstrosityRailgun",
		"CGESanctifiedMonstrosityPusGround",
	},
	modList = {
		-- CleansedMonsterNoEquipmentDrops [drop_no_equipment = 1]
	},
}

-- Dinosaur
minions["Metadata/Monsters/BoneCultists/BoneCultists_Beast/BoneCultistBeast"] = {
	name = "Drudge Osseodon",
	monsterTags = { "beast", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", "reptile_beast", "slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.75,
	damageSpread = 0.2,
	attackTime = 1.665,
	attackRange = 19,
	accuracy = 1,
	spectreReservation = 130,
	companionReservation = 47.4,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"CultistBeastSunder",
	},
	modList = {
	},
}

-- Faridun
minions["Metadata/Monsters/Mutewind/MutewindWomanSpearSandCrusted"] = {
	name = "Faridun Spearwoman",
	monsterTags = { "fast_movement", "human", "humanoid", "melee", "not_int", "not_str", "physical_affinity", "red_blood", "SpearMetal_onhit_audio", },
	life = 1.1,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.8,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 21,
	accuracy = 1,
	weaponType1 = "Spear",
	spectreReservation = 60,
	companionReservation = 31.5,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"EmptyActionMutewindBanditLeap",
		"MutewindBanditWomanLeap",
		"EmptyActionMutewindBanditCombo",
		"MutewindBanditWomanCombo1",
		"MutewindBanditWomanCombo2",
		"MutewindBanditWomanCombo3",
		"WalkEmergeMutewind",
		"GAMutewindWomanSpearStab1",
		"GAMutewindWomanSpearStab2",
	},
	modList = {
	},
}

-- Filthy First-born
minions["Metadata/Monsters/Cenobite/CenobiteBloater/CenobiteBloater"] = {
	name = "Filthy First-born",
	monsterTags = { "allows_inc_aoe", "humanoid", "melee", "monster_has_on_death_mechanic", "MonsterBlunt_onhit_audio", "no_minion_revival", "not_dex", "not_int", "physical_affinity", "red_blood", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.75,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 3.99,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "Two Handed Mace",
	spectreReservation = 130,
	companionReservation = 47.4,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeed",
		"GSCenobiteBloaterOnDeath",
		"GACenobiteBloaterSlam",
	},
	modList = {
		-- SpectrePlayDeathAction [is_spectre_with_death_action = 1]
	},
}

-- Goliath
minions["Metadata/Monsters/TwoheadedTitan/TwoHeadedTitan"] = {
	name = "Goliath",
	monsterTags = { "allows_inc_aoe", "humanoid", "melee", "MonsterBlunt_onhit_audio", "physical_affinity", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 20,
	accuracy = 1,
	spectreReservation = 130,
	companionReservation = 47.4,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeed",
		"GATwoHeadedTitanSlam",
		"GATwoHeadedTitanStomp",
	},
	modList = {
	},
}

-- Scarab
minions["Metadata/Monsters/EtchedBeetles/MediumEtchedBeetleArmouredDull"] = {
	name = "Tarnished Scarab",
	monsterTags = { "2HSharpMetal_onhit_audio", "allows_inc_aoe", "beast", "fast_movement", "insect", "lightning_affinity", "melee", "not_dex", "not_int", },
	life = 1.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.7,
	fireResist = 0,
	coldResist = -30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	spectreReservation = 80,
	companionReservation = 36.6,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeed",
		"GAMediumBeetleChargedSunder",
		"GAMediumBeetleSunder",
	},
	modList = {
	},
}

-- Sentinel
minions["Metadata/Monsters/VaalConstructs/Sentinel/VaalConstructSentinel"] = {
	name = "Stone Sentinel",
	monsterTags = { "2HBluntWood_onhit_audio", "allows_inc_aoe", "cannot_be_monolith", "construct", "melee", "not_dex", "not_int", "physical_affinity", "stone_construct", "vaal", "very_slow_movement", },
	life = 2.5,
	baseDamageIgnoresAttackSpeed = true,
	armour = 1,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 13,
	accuracy = 1,
	spectreReservation = 130,
	companionReservation = 47.4,
	monsterCategory = "Construct",
	skillList = {
		"MeleeAtAnimationSpeed",
		"GAVaalConstructSentinelGroundSlam",
		"GAVaalConstructSentinelFootSlam",
		"GAVaalConstructSentinelImpact",
	},
	modList = {
	},
}

-- Serpent Shaman
minions["Metadata/Monsters/SerpentClanMonster/SerpentClanCaster"] = {
	name = "Serpent Shaman",
	monsterTags = { "allows_additional_projectiles", "allows_inc_aoe", "beast", "Beast_onhit_audio", "caster", "fast_movement", "humanoid", "not_dex", "not_str", "physical_affinity", "reptile_beast", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.02,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 10,
	accuracy = 1,
	spectreReservation = 100,
	companionReservation = 42.3,
	monsterCategory = "Beast",
	skillList = {
		"MeleeAtAnimationSpeed",
		"SerpentClanTailWhip",
		"SerpentClanCurse",
		"DeceleratingProjectileSerpentClan",
		"GSSerpentClanSpellNova",
		"SSMSerpentClanVulnerability",
	},
	modList = {
	},
}

-- Shade
minions["Metadata/Monsters/VaalMonsters/Machinarium/Wraith/ProwlingShade"] = {
	name = "Prowling Shade",
	monsterTags = { "allows_inc_aoe", "caster", "Claw_onhit_audio", "cold_affinity", "fast_movement", "ghost", "ghost_blood", "melee", "not_str", "undead", },
	life = 2.25,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.132,
	evasion = 0.33,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2.25,
	damageSpread = 0.2,
	attackTime = 1.32,
	attackRange = 16,
	accuracy = 1,
	spectreReservation = 110,
	companionReservation = 45,
	monsterCategory = "Undead",
	skillList = {
		"MeleeAtAnimationSpeedComboTEMP",
		"GSProwlingShadeIceBeam",
		"DTTProwlingShadeDash",
		"MeleeAtAnimationSpeedComboTEMP2",
	},
	modList = {
	},
}

--Terracotta Soldier
minions["Metadata/Monsters/TerracottaGuardians/TerracottaGuardianSceptre"] = {
	name = "Terracotta Soldier",
	monsterTags = { "1HBluntMetal_onhit_audio", "construct", "melee", "not_dex", "not_int", "physical_affinity", "very_slow_movement", },
	life = 1.54,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.5,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.27,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	spectreReservation = 60,
	companionReservation = 31.5,
	monsterCategory = "Construct",
	skillList = {
		"MeleeAtAnimationSpeed",
		"EGTerracottaTransitionSideways",
		"EGTerracottaTransition",
	},
	modList = {
	},
}
minions["Metadata/Monsters/TerracottaGuardians/TerracottaGuardianSceptreAmbush__"] = {
	name = "Terracotta Soldier",
	monsterTags = { "1HBluntMetal_onhit_audio", "construct", "melee", "not_dex", "not_int", "physical_affinity", "very_slow_movement", },
	life = 0.99,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.5,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.88,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	spectreReservation = 10,
	companionReservation = 14.1,
	monsterCategory = "Construct",
	skillList = {
		"MeleeAtAnimationSpeed",
	},
	modList = {
	},
}

-- Quadrilla
minions["Metadata/Monsters/Quadrilla/Quadrilla"] = {
	name = "Quadrilla",
	monsterTags = { "allows_inc_aoe", "beast", "fast_movement", "mammal_beast", "melee", "MonsterBlunt_onhit_audio", "not_dex", "not_int", "physical_affinity", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	armour = 0.75,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 21,
	accuracy = 1,
	spectreReservation = 100,
	companionReservation = 42.3,
	monsterCategory = "Beast",
	skillList = {
		"GAQuadrillaSunder",
		"EAAQuadrillaThrow",
		"MeleeAtAnimationSpeed",
		"GPAQuadrillaRock",
		"SSMQuadrillaRock",
		"QuadrillaShieldCharge",
		"TCQuadrillaCharge",
		"EASQuadrillaTaunt",
	},
	modList = {
	},
}

-- Vaal Humanoid
minions["Metadata/Monsters/VaalMonsters/Living/VaalGuardMortarLiving"] = {
	name = "Vaal Guard",
	monsterTags = { "allows_additional_projectiles", "allows_inc_aoe", "fire_affinity", "human", "humanoid", "not_int", "not_str", "ranged", "red_blood", "Unarmed_onhit_audio", "very_slow_movement", },
	life = 1,
	baseDamageIgnoresAttackSpeed = true,
	evasion = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	spectreReservation = 50,
	companionReservation = 30,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeed",
		"MMSVaalGuardGrenade",
		"MMSVaalGuardOilTrap",
		"MMSVaalGuardGrenadeDeath",
		"MMSVaalGuardOilTrapDeath",
	},
	modList = {
		-- SpectrePlayDeathAction [is_spectre_with_death_action = 1]
	},
}
minions["Metadata/Monsters/VaalMonsters/Living/BloodPriests/VaalBloodPriestMale"] = {
	name = "Blood Priest",
	monsterTags = { "1HSword_onhit_audio", "allows_additional_projectiles", "allows_inc_aoe", "caster", "cultist", "fast_movement", "human", "humanoid", "not_str", "physical_affinity", "ranged", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.08,
	evasion = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "Dagger",
	spectreReservation = 100,
	companionReservation = 42.3,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeed",
		"VaalBloodPriestExsanguinate",
		"VaalBloodPriestDetonateDead",
		"MPSVaalBloodPriestProj",
		"EGBloodPriestSacrifice",
		"EASBloodPriestSummonElemental",
		"CGEBloodPriestBoilingBlood",
	},
	modList = {
	},
}
minions["Metadata/Monsters/VaalMonsters/Living/BloodPriests/VaalBloodPriestFemale"] = {
	name = "Blood Priestess",
	monsterTags = { "1HSword_onhit_audio", "allows_additional_projectiles", "allows_inc_aoe", "caster", "cultist", "fast_movement", "human", "humanoid", "not_str", "physical_affinity", "ranged", "red_blood", },
	life = 2,
	baseDamageIgnoresAttackSpeed = true,
	energyShield = 0.08,
	evasion = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "Dagger",
	spectreReservation = 100,
	companionReservation = 42.3,
	monsterCategory = "Humanoid",
	skillList = {
		"MeleeAtAnimationSpeed",
		"VaalBloodPriestSoulrend",
		"EGBloodPriestVolatileDead",
		"MPSVaalBloodPriestProj",
		"EGBloodPriestSacrifice",
		"EASBloodPriestSummonElemental",
	},
	modList = {
	},
}
