-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Tamed Beast (Companion) Modifier Data
-- Monster data (c) Grinding Gear Games

local mods, mod, flag = ...

mods["PlayerMonsterDamageGainedAsFire1"] = {
	name = "Extra Fire Damage",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "fire_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Gains 40% of damage as extra Fire damage.",
	},
	modList = {
		mod("DamageGainAsFire", "BASE", 40, 0, 0), -- PlayerMonsterDamageGainedAsFire1 [non_skill_base_all_damage_%_to_gain_as_fire = 40]
	},
}

mods["PlayerMonsterDamageGainedAsCold1"] = {
	name = "Extra Cold Damage",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "cold_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Gains 40% of damage as extra Cold damage.",
	},
	modList = {
		mod("DamageGainAsCold", "BASE", 40, 0, 0), -- PlayerMonsterDamageGainedAsCold1 [non_skill_base_all_damage_%_to_gain_as_cold = 40]
	},
}

mods["PlayerMonsterDamageGainedAsLightning1"] = {
	name = "Extra Lightning Damage",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "lightning_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Gains 40% of damage as extra Lightning damage.",
	},
	modList = {
		mod("DamageGainAsLightning", "BASE", 40, 0, 0), -- PlayerMonsterDamageGainedAsLightning1 [non_skill_base_all_damage_%_to_gain_as_lightning = 40]
	},
}

mods["PlayerMonsterIncreasedSpeed1"] = {
	name = "Hasted",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "fast_movement", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 30% increased Attack, Cast and Movement speed.",
	},
	modList = {
		mod("Speed", "INC", 30, 0, 0), -- PlayerMonsterIncreasedSpeed1 [attack_and_cast_speed_+% = 30]
		mod("MovementSpeed", "INC", 30, 0, 0), -- PlayerMonsterIncreasedSpeed1 [base_movement_velocity_+% = 30]
	},
}

mods["PlayerMonsterCriticalStrikeChance1"] = {
	name = "Extra Crits",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 300% increased chance to Critically Hit.",
	},
	modList = {
		mod("CritChance", "INC", 300, 0, 0), -- PlayerMonsterCriticalStrikeChance1 [critical_strike_chance_+% = 300]
	},
}

mods["PlayerMonsterStunDamageIncrease1"] = {
	name = "Stuns",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "melee", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 100% increased Stun buildup.",
	},
	modList = {
		-- PlayerMonsterStunDamageIncrease1 [hit_damage_stun_multiplier_+% = 100]
	},
}

mods["PlayerMonsterExtraArmour1"] = {
	name = "Armoured",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "armour", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster gains extra Armour based off of their Strength.",
	},
	modList = {
		-- PlayerMonsterExtraArmour1 [monster_additional_strength_ratio_%_for_armour = 100]
	},
}

mods["PlayerMonsterExtraEvasion1"] = {
	name = "Evasive",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "evasion", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster gains extra Evasion based off of their Dexterity.",
	},
	modList = {
		-- PlayerMonsterExtraEvasion1 [monster_additional_dexterity_ratio_%_for_evasion = 100]
	},
}

mods["PlayerMonsterExtraEnergyShield1"] = {
	name = "Extra Energy Shield",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "energy_shield", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster gains 25% of Maximum life as added Energy Shield.",
	},
	modList = {
		-- PlayerMonsterExtraEnergyShield1 [base_maximum_life_%_to_gain_as_total_energy_shield = 25]
	},
}

mods["PlayerMonsterAlwaysPoison1"] = {
	name = "Always Poisons",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "physical_affinity", weight = 1 },
		{ tag = "chaos_affinity", weight = 1 },
		{ tag = "default", weight = 0 },
	},
	statDescriptions = {
	},
	modList = {
		mod("PoisonChance", "BASE", 100, 0, 0), -- PlayerMonsterAlwaysPoison1 [global_poison_on_hit = 1]
	},
}

mods["PlayerMonsterAlwaysBleed1"] = {
	name = "Always Bleeds",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "physical_affinity", weight = 1 },
		{ tag = "default", weight = 0 },
	},
	statDescriptions = {
	},
	modList = {
		mod("BleedChance", "BASE", 100, 0, 0), -- PlayerMonsterAlwaysBleed1 [global_bleed_on_hit = 1]
	},
}

mods["PlayerMonsterBurningGroundOnDeath1"] = {
	name = "Periodically unleashes Fire",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "titan_boss", weight = 0 },
		{ tag = "fire_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterChilledGroundOnDeath1"] = {
	name = "Periodically unleashes Ice",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "titan_boss", weight = 0 },
		{ tag = "cold_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterShockedGroundOnDeath1"] = {
	name = "Periodically unleashes Lightning",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "titan_boss", weight = 0 },
		{ tag = "lightning_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterStunResilience1"] = {
	name = "Stun Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 250% increased Stun Threshold.",
	},
	modList = {
		mod("StunThreshold", "INC", 250, 0, 0), -- PlayerMonsterStunResilience1 [stun_threshold_+% = 250]
	},
}

mods["PlayerMonsterFireResistance1"] = {
	name = "Fire Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "fire_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has +50% to Fire Resistance and +10% to Maximum Fire Resistance.",
	},
	modList = {
		mod("FireResist", "BASE", 50, 0, 0), -- PlayerMonsterFireResistance1 [base_fire_damage_resistance_% = 50]
		mod("FireResistMax", "BASE", 10, 0, 0), -- PlayerMonsterFireResistance1 [base_maximum_fire_damage_resistance_% = 10]
	},
}

mods["PlayerMonsterColdResistance1"] = {
	name = "Cold Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "cold_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has +50% to Cold Resistance and +10% to Maximum Cold Resistance.",
	},
	modList = {
		mod("ColdResist", "BASE", 50, 0, 0), -- PlayerMonsterColdResistance1 [base_cold_damage_resistance_% = 50]
		mod("ColdResistMax", "BASE", 10, 0, 0), -- PlayerMonsterColdResistance1 [base_maximum_cold_damage_resistance_% = 10]
	},
}

mods["PlayerMonsterLightningResistance1"] = {
	name = "Lightning Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "lightning_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has +50% to Lightning Resistance and +10% to Maximum Lightning Resistance.",
	},
	modList = {
		mod("LightningResist", "BASE", 50, 0, 0), -- PlayerMonsterLightningResistance1 [base_lightning_damage_resistance_% = 50]
		mod("LightningResistMax", "BASE", 10, 0, 0), -- PlayerMonsterLightningResistance1 [base_maximum_lightning_damage_resistance_% = 10]
	},
}

mods["PlayerMonsterArmourPenetration1"] = {
	name = "Breaks Armour",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Breaks Armour equal to 1000% of Physical Damage dealt.",
	},
	modList = {
		mod("Condition:CanArmourBreak", "FLAG", 1000, 0, 0, { effectName = "ArmourBreak", effectType = "Buff", type = "GlobalEffect" }), -- PlayerMonsterArmourPenetration1 [armour_break_physical_damage_%_dealt_as_armour_break = 1000]
	},
}

mods["PlayerMonsterIncreasedAccuracy1"] = {
	name = "Accurate",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 200% increased Accuracy Rating.",
	},
	modList = {
		mod("Accuracy", "INC", 200, 0, 0), -- PlayerMonsterIncreasedAccuracy1 [accuracy_rating_+% = 200]
	},
}

mods["PlayerMonsterDamageGainedAsChaos1"] = {
	name = "Extra Chaos Damage",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "chaos_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Gains 40% of damage as extra Chaos damage.",
	},
	modList = {
		mod("DamageGainAsChaos", "BASE", 40, 0, 0), -- PlayerMonsterDamageGainedAsChaos1 [non_skill_base_all_damage_%_to_gain_as_chaos = 40]
	},
}

mods["PlayerMonsterLifeRegenerationRatePercentage1"] = {
	name = "Regenerates Life",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster Regenerates 2% of Maximum Life per second.",
	},
	modList = {
		mod("LifeRegenPercent", "BASE", 2, 0, 0), -- PlayerMonsterLifeRegenerationRatePercentage1 [life_regeneration_rate_per_minute_% = 120]
	},
}

mods["PlayerMonsterAdditionalProjectiles1"] = {
	name = "Additional Projectiles",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "allows_additional_projectiles", weight = 1 },
		{ tag = "default", weight = 0 },
	},
	statDescriptions = {
		"Monster fires 4 additional Projectiles.",
	},
	modList = {
		mod("ProjectileCount", "BASE", 4, 0, 0), -- PlayerMonsterAdditionalProjectiles1 [number_of_additional_projectiles = 4]
	},
}

mods["PlayerMonsterAreaOfEffect1"] = {
	name = "Increased Area of Effect",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "allows_inc_aoe", weight = 1 },
		{ tag = "default", weight = 0 },
	},
	statDescriptions = {
		"Monster has 100% Increased Area of Effect.",
		"100% more Area of Effect",
	},
	modList = {
		-- PlayerMonsterAreaOfEffect1 [rare_monster_mod_area_of_effect_+%_final = 100]
	},
}

mods["PlayerMonsterIgniteChanceIncrease1"] = {
	name = "All Damage Ignites",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "fire_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
		mod("PhysicalCanIgnite", "FLAG", 1, 0, 0), -- PlayerMonsterIgniteChanceIncrease1 [all_damage_can_ignite = 1]
		mod("EnemyIgniteChance", "BASE", 100, 0, 0), -- PlayerMonsterIgniteChanceIncrease1 [always_ignite = 1]
	},
}

mods["PlayerMonsterFreezeDamageIncrease1"] = {
	name = "All Damage Chills",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "cold_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
		-- PlayerMonsterFreezeDamageIncrease1 [all_damage_can_chill = 1]
		-- PlayerMonsterFreezeDamageIncrease1 [chill_minimum_slow_% = 10]
	},
}

mods["PlayerMonsterShockChanceIncrease1"] = {
	name = "All Damage Shocks",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "lightning_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
		mod("PhysicalCanShock", "FLAG", 1, 0, 0), -- PlayerMonsterShockChanceIncrease1 [all_damage_can_shock = 1]
		mod("EnemyShockChance", "BASE", 100, 0, 0), -- PlayerMonsterShockChanceIncrease1 [always_shock = 1]
	},
}

mods["PlayerMonsterBurningGroundTrail1"] = {
	name = "Trail of Fire",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "immobile", weight = 0 },
		{ tag = "ranged", weight = 0 },
		{ tag = "fire_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterChilledGroundTrail1"] = {
	name = "Trail of Ice",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "immobile", weight = 0 },
		{ tag = "ranged", weight = 0 },
		{ tag = "cold_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterShockedGroundTrail1"] = {
	name = "Trail of Lightning",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "immobile", weight = 0 },
		{ tag = "ranged", weight = 0 },
		{ tag = "lightning_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster leaves a trail of Shocked Ground as they move.",
	},
	modList = {
	},
}

mods["PlayerMonsterImmuneToSlow1"] = {
	name = "Slow Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has 50% reduced Slowing Potency of Debuffs on them.",
		"50% less Slowing Potency of Debuffs on me",
	},
	modList = {
		-- PlayerMonsterImmuneToSlow1 [monster_slow_potency_+%_final = -50]
	},
}

mods["PlayerMonsterModReducedCritMulti1"] = {
	name = "Crit Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Hits against this Monster have 80% reduced Critical Damage Bonus.",
	},
	modList = {
		mod("SelfCritMultiplier", "INC", -80, 0, 0), -- PlayerMonsterModReducedCritMulti1 [base_self_critical_strike_multiplier_-% = 80]
	},
}

mods["PlayerMonsterChaosResistance1"] = {
	name = "Chaos Resistant",
	type = "Suffix",
	tier = 1,
	spawnWeights = {
		{ tag = "chaos_affinity", weight = 1 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster has +50% to Chaos Resistance.",
	},
	modList = {
		mod("ChaosResist", "BASE", 50, 0, 0), -- PlayerMonsterChaosResistance1 [base_chaos_damage_resistance_% = 50]
	},
}

mods["PlayerMonsterFlameBeacons1"] = {
	name = "Periodic Fire Explosions",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterFrostBeacons1"] = {
	name = "Periodic Cold Explosions",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterLightningBeacons1"] = {
	name = "Periodic Lightning Explosions",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterStrongerMinions1"] = {
	name = "Powerful Minions",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster's Pack Minions have 25% increased Damage and 50% increased Life.",
	},
	modList = {
	},
}

mods["PlayerMonsterPhysicalDamageAura1"] = {
	name = "Extra Physical Damage Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that grants 40% increased Physical Damage to Allies within 5 metres.",
	},
	modList = {
		mod("PhysicalDamage", "INC", 40, 0, 0), -- PlayerMonsterPhysicalDamageAura1 [physical_damage_+% = 40]
	},
}

mods["PlayerMonsterIncreasedSpeedAura1"] = {
	name = "Haste Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "fast_movement", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that grants 20% increased Attack and Cast speed and 10% increased Movement speed to Allies within 5 metres.",
	},
	modList = {
		mod("Speed", "INC", 25, 0, 0), -- PlayerMonsterIncreasedSpeedAura1 [attack_and_cast_speed_+% = 25]
		mod("MovementSpeed", "INC", 25, 0, 0), -- PlayerMonsterIncreasedSpeedAura1 [base_movement_velocity_+% = 25]
	},
}

mods["PlayerMonsterEnergyShieldAura1"] = {
	name = "Energy Shield Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that grants 20% of Maximum life as added Energy Shield to Allies within 5 metres.",
	},
	modList = {
		-- PlayerMonsterEnergyShieldAura1 [base_maximum_life_%_to_gain_as_total_energy_shield = 30]
	},
}

mods["PlayerMonsterResistanceAura1"] = {
	name = "Elemental Resistance Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that grants +35% to all Elemental Resistances to Allies within 5 metres.",
	},
	modList = {
		mod("ElementalResist", "BASE", 35, 0, 0), -- PlayerMonsterResistanceAura1 [base_resist_all_elements_% = 35]
	},
}

mods["PlayerMonsterTemporalAura1"] = {
	name = "Temporal Bubble",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that Debuffs Enemies within 3.2 metres; Slowing by 25%, making effects expire 40% slower and reducing Cooldown Recovery Rate by 60%.",
	},
	modList = {
		-- PlayerMonsterTemporalAura1 [action_speed_-% = 25]
		-- PlayerMonsterTemporalAura1 [debuff_time_passed_+% = -40]
		mod("CooldownRecovery", "INC", -60, 0, 0), -- PlayerMonsterTemporalAura1 [base_cooldown_speed_+% = -60]
		-- PlayerMonsterTemporalAura1 [cannot_be_damaged_by_things_outside_radius = 0]
	},
}

mods["PlayerMonsterHinderAura1"] = {
	name = "Hinder Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that Hinders enemies within 3.6 metres.",
	},
	modList = {
	},
}

mods["PlayerMonsterPreventRecoveryAura1"] = {
	name = "Prevents Recovery Above 50%",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that Debuffs enemies within 4.2 metres, causing their Life and Energy Shield to not be able to recover past 50%.",
	},
	modList = {
	},
}

mods["PlayerMonsterImmuneAura1"] = {
	name = "Periodic Invulnerability Aura",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster releases a nova that makes Allies invulnerable for 5 seconds while the monster is alive within 5 metres every 12 seconds.",
	},
	modList = {
		-- PlayerMonsterImmuneAura1 [monster_allies_cannot_take_damage_pulse_owner = 1]
	},
}

mods["PlayerMonsterImmuneAura2"] = {
	name = "Empowered Periodic Invulnerability Aura",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster releases a nova that makes Allies invulnerable for 5 seconds while the monster is alive within 5 metres every 12 seconds.",
	},
	modList = {
		-- PlayerMonsterImmuneAura2 [monster_allies_cannot_take_damage_pulse_owner = 1]
	},
}

mods["PlayerMonsterManaSiphonAura1"] = {
	name = "Siphons Mana and Deals Lightning Damage",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "ranged", weight = 0 },
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates a circular effect that drains Mana and deals Lightning Damage over time to enemies near the edge of the circle.",
	},
	modList = {
	},
}

mods["PlayerMonsterManaSiphonAura2"] = {
	name = "Siphons Mana and Deals Lightning Damage",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "ranged", weight = 0 },
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates a circular effect that drains Mana and deals Lightning Damage over time to enemies near the edge of the circle. Additionally, Monster will periodically create separate circles that drain Mana and deal Lightning Damage over time to enemies standing in them.",
	},
	modList = {
	},
}

mods["PlayerMonsterHealingNova1"] = {
	name = "Heals Allies and Suppresses Foe Recovery",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster releases a nova that reduces Enemy Life and Energy Shield Recovery Rate by 60% and causes Allies to Regenerate 5.5% of Maximum Life per second for 4 seconds within 5 metres every 8 seconds.",
	},
	modList = {
	},
}

mods["PlayerMonsterFlaskRemovalAura1"] = {
	name = "Siphons Flask Charges",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates an Aura that removes 3 Flask and Charm charges from enemies every 3 seconds within 3.6 metres.",
	},
	modList = {
		-- PlayerMonsterFlaskRemovalAura1 [generate_x_charges_for_any_flask_per_minute = -3]
	},
}

mods["PlayerMonsterRevivesMinions1"] = {
	name = "Reviving Minions",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "quest_null_monster_mods", weight = 0 },
		{ tag = "boss", weight = 0 },
		{ tag = "no_minion_revival", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically revives Pack Minions.",
	},
	modList = {
	},
}

mods["PlayerMonsterRevivesMinions2"] = {
	name = "Empowered Reviving Minions",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "quest_null_monster_mods", weight = 0 },
		{ tag = "boss", weight = 0 },
		{ tag = "no_minion_revival", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically revives Pack Minions with increased Life and Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterMinionsTakeLifeInstead1"] = {
	name = "Damage Taken From Minions First",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "boss", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"50% of damage taken from Monster is taken from Monster's Pack Minions instead",
	},
	modList = {
		-- PlayerMonsterMinionsTakeLifeInstead1 [damage_removed_from_pack_minions_before_life_or_es_% = 50]
	},
}

mods["PlayerMonsterShroudWalker1"] = {
	name = "Shroud Walker",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "immobile", weight = 0 },
		{ tag = "no_shroud_walker", weight = 0 },
		{ tag = "boss", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically teleports to an enemy they can see, creating a Smoke Cloud where they leave and where they teleport to.",
	},
	modList = {
	},
}

mods["PlayerMonsterShroudWalker2"] = {
	name = "Shroud Walker",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "immobile", weight = 0 },
		{ tag = "no_shroud_walker", weight = 0 },
		{ tag = "boss", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically teleports to an enemy they can see, creating a Smoke Cloud where they leave and where they teleport to.",
	},
	modList = {
	},
}

mods["PlayerMonsterPeriodicEnrage1"] = {
	name = "Periodically Enrages",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically Enrages; gaining 30% increased Damage, 25% increased Skill and Movement Speed and 33% less damage taken for 5 seconds every 10 seconds.",
	},
	modList = {
	},
}

mods["PlayerMonsterPeriodicEnrage2"] = {
	name = "Enraged",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster is Enraged; gaining 30% increased Damage, 25% increased Skill and Movement Speed and 33% less damage taken.",
	},
	modList = {
	},
}

mods["PlayerMonsterCorpseExploder1"] = {
	name = "Explodes Nearby Corpses",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterLightningMirage1"] = {
	name = "Lightning Mirage When Hit",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates a Mirage when Hit that moves towards enemies and explodes when it gets close enough, dealing Lightning Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterLightningMirage2"] = {
	name = "Lightning Mirages When Hit",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates Mirages when Hit that move towards enemies and explode when they get close enough, dealing Lightning Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterMagmaBarrier1"] = {
	name = "Magma Barrier",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates a 90% damage absorption barrier that explodes after taking a certain amount of damage, dealing Fire Damage",
	},
	modList = {
	},
}

mods["PlayerMonsterFlamewaller1"] = {
	name = "Conjures Flamewalls",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "sanctum_monster", weight = 0 },
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster creates circular walls of Fire that deal damage to enemies standing in them.",
	},
	modList = {
	},
}

mods["PlayerMonsterLightningStorms1"] = {
	name = "Conjures Lightning Storms",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
	},
	modList = {
	},
}

mods["PlayerMonsterVolatilePlants1"] = {
	name = "Volatile Plants",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically creates Volatile Plants, releasing orbs that move towards enemies; exploding when they get close enough; dealing Chaos Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterVolatilePlants2"] = {
	name = "Empowering Volatile Plants",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically creates Powerful Volatile Plants, releasing orbs that move towards enemies; exploding when they get close enough; dealing Chaos Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterVolatileRocks1"] = {
	name = "Volatile Crag",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically creates Volatile Crag that moves towards enemies; exploding when they get close enough; dealing Fire Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterVolatileRocks2"] = {
	name = "Empowering Volatile Crag",
	type = "Prefix",
	tier = 2,
	spawnWeights = {
		{ tag = "magic", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster periodically creates Powerful Volatile Crag that moves towards enemies; exploding when they get close enough; dealing Fire Damage.",
	},
	modList = {
	},
}

mods["PlayerMonsterProximalTangibility1"] = {
	name = "Proximal Tangibility",
	type = "Prefix",
	tier = 1,
	spawnWeights = {
		{ tag = "no_proximity_shield", weight = 0 },
		{ tag = "boss", weight = 0 },
		{ tag = "default", weight = 1 },
	},
	statDescriptions = {
		"Monster cannot be damaged by enemies any further than 3 metres from them.",
	},
	modList = {
		-- PlayerMonsterProximalTangibility1 [ignore_cannot_be_damaged_by_enemies = 0]
	},
}
