name: Sync Release to Master

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  sync-release-to-master:
    # Checks that the push to dev was from a pull request whose head branch started with 'release-'.
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Configure bot user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Merge fast-forward dev into master
        run: |
          git merge ${{ github.sha }} --ff-only
          git push
